In [1]:
#Load packages
import pandas as pd
import numpy as np

# I. Coding Run Expectancy Dataset (2017)

In [34]:
# Read in MLBAM Data for 2017

MLBAM17 = pd.read_csv("../Data/MLBAM17.csv")

In [35]:
#Your Code Here
# Here we create a df RE18 which includes only columns we need to calculate the run expectancy matrix.

RE17 = MLBAM17[['batterName','batterId','event', 'start1B', 'start2B', 'start3B', 'end1B', 'end2B', 'end3B',\
                   'startOuts','endOuts','runsFuture','runsOnPlay','outsInInning',\
                   'stand', 'throws','venueId', 'stadium', 'batterPos']].copy()

display(RE17)

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,endOuts,runsFuture,runsOnPlay,outsInInning,stand,throws,venueId,stadium,batterPos
0,Gardner,458731,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,R,12,Tropicana Field,LF
1,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,R,R,12,Tropicana Field,C
2,Bird,595885,Walk,NaN,NaN,NaN,595885.0,NaN,NaN,2,2,0,0,3,L,R,12,Tropicana Field,1B
3,Holliday,407812,Groundout,595885.0,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,R,12,Tropicana Field,DH
4,"Dickerson, C",572816,Single,NaN,NaN,NaN,572816.0,NaN,NaN,0,0,3,0,3,L,R,12,Tropicana Field,DH
5,Kiermaier,595281,Double,572816.0,NaN,NaN,NaN,595281.0,572816.0,0,0,3,0,3,L,R,12,Tropicana Field,CF
6,Longoria,446334,Sac Fly,NaN,595281.0,572816.0,NaN,595281.0,NaN,0,1,3,1,3,R,R,12,Tropicana Field,3B
7,"Miller, B",543543,Single,NaN,595281.0,NaN,543543.0,NaN,595281.0,1,1,2,0,3,L,R,12,Tropicana Field,2B
8,Souza Jr.,519306,Walk,543543.0,NaN,595281.0,519306.0,543543.0,595281.0,1,1,2,0,3,R,R,12,Tropicana Field,RF
9,Morrison,489149,Single,519306.0,543543.0,595281.0,489149.0,519306.0,NaN,1,1,2,2,3,L,R,12,Tropicana Field,1B
10,Beckham,542921,Lineout,489149.0,519306.0,NaN,489149.0,519306.0,NaN,1,2,0,0,3,R,R,12,Tropicana Field,SS
11,"Smith, M",605480,Strikeout,489149.0,519306.0,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,12,Tropicana Field,LF
12,Ellsbury,453056,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,2,0,3,L,R,12,Tropicana Field,CF
13,"Castro, S",516770,Single,NaN,NaN,NaN,516770.0,NaN,NaN,1,1,2,0,3,R,R,12,Tropicana Field,2B
14,Headley,452104,Single,516770.0,NaN,NaN,452104.0,516770.0,NaN,1,1,2,0,3,L,R,12,Tropicana Field,3B
15,Judge,592450,Double,452104.0,516770.0,NaN,NaN,592450.0,452104.0,1,1,2,1,3,R,R,12,Tropicana Field,RF
16,Torreyes,591720,Groundout,NaN,592450.0,452104.0,NaN,NaN,592450.0,1,2,1,1,3,R,R,12,Tropicana Field,SS
17,Gardner,458731,Groundout,NaN,NaN,592450.0,NaN,NaN,NaN,2,3,0,0,3,L,R,12,Tropicana Field,LF
18,"Norris, De",519083,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,2,0,3,R,R,12,Tropicana Field,C
19,"Dickerson, C",572816,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,2,0,3,L,R,12,Tropicana Field,DH
20,Kiermaier,595281,Walk,NaN,NaN,NaN,595281.0,NaN,NaN,2,2,2,0,3,L,R,12,Tropicana Field,CF
21,Longoria,446334,Home Run,595281.0,NaN,NaN,NaN,NaN,NaN,2,2,2,2,3,R,R,12,Tropicana Field,3B
22,"Miller, B",543543,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,12,Tropicana Field,2B
23,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,R,R,12,Tropicana Field,C
24,Bird,595885,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,L,R,12,Tropicana Field,1B
25,Holliday,407812,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,R,12,Tropicana Field,DH
26,Souza Jr.,519306,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,2,0,3,R,R,12,Tropicana Field,RF
27,Morrison,489149,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,1,2,1,3,L,R,12,Tropicana Field,1B
28,Beckham,542921,Double,NaN,NaN,NaN,NaN,542921.0,NaN,1,1,1,0,3,R,R,12,Tropicana Field,SS
29,"Smith, M",605480,Single,NaN,542921.0,NaN,NaN,605480.0,NaN,1,1,1,1,3,L,R,12,Tropicana Field,LF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185565,Duvall,594807,Double,NaN,NaN,NaN,NaN,594807.0,NaN,1,1,1,0,3,R,L,17,Wrigley Field,LF
185566,Suarez,553993,Single,NaN,594807.0,NaN,553993.0,NaN,594807.0,1,1,1,0,3,R,L,17,Wrigley Field,3B
185567,Gennett,571697,Single,553993.0,NaN,594807.0,571697.0,553993.0,NaN,1,1,1,1,3,L,L,17,Wrigley Field,2B
185568,Ervin,640447,Lineout,571697.0,553993.0,NaN,571697.0,553993.0,NaN,1,2,0,0,3,R,L,17,Wrigley Field,RF
185569,Wallach,595453,Strikeout,571697.0,553993.0,NaN,NaN,NaN,NaN,2,3,0,0,3,R,L,17,Wrigley Field,UN
185570,"Davis, T",543089,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,R,R,17,Wrigley Field,UN
185571,Almora Jr.,546991,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,R,R,17,Wrigley Field,UN
185572,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,17,Wrigley Field,UN
185573,Kivlehan,623182,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,R,R,17,Wrigley Field,UN
185574,Hamilton,571740,Lineout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,L,R,17,Wrigley Field,CF
185575,Vincej,572227,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,R,17,Wrigley Field,UN
185576,Zobrist,450314,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,R,L,17,Wrigley Field,LF
185577,"Pena, Fe",570240,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,R,L,17,Wrigley Field,UN
185578,Schwarber,656941,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,L,L,17,Wrigley Field,UN
185579,Votto,458015,Double,NaN,NaN,NaN,NaN,458015.0,NaN,0,0,0,0,3,L,R,17,Wrigley Field,1B
185580,Duvall,594807,Strikeout,NaN,458015.0,NaN,NaN,458015.0,NaN,0,1,0,0,3,R,R,17,Wrigley Field,LF
185581,Suarez,553993,Flyout,NaN,458015.0,NaN,NaN,458015.0,NaN,1,2,0,0,3,R,R,17,Wrigley Field,3B
185582,Gennett,571697,Strikeout,NaN,458015.0,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,17,Wrigley Field,2B
185583,Caratini,605170,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,R,17,Wrigley Field,UN
185584,La Stella,600303,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,L,R,17,Wrigley Field,UN
185585,"Happ, I",664023,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,17,Wrigley Field,UN
185586,Ervin,640447,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,R,R,17,Wrigley Field,RF
185587,Wallach,595453,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,R,R,17,Wrigley Field,UN
185588,Winker,608385,Single,NaN,NaN,NaN,608385.0,NaN,NaN,2,2,0,0,3,L,R,17,Wrigley Field,UN
185589,Hamilton,571740,Walk,608385.0,NaN,NaN,571740.0,608385.0,NaN,2,2,0,0,3,L,R,17,Wrigley Field,CF
185590,Vincej,572227,Runner Out,571740.0,608385.0,NaN,NaN,NaN,NaN,2,3,0,0,3,R,R,17,Wrigley Field,UN
185591,"Davis, T",543089,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1,0,3,R,R,17,Wrigley Field,UN
185592,Almora Jr.,546991,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,3,R,R,17,Wrigley Field,UN
185593,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,L,R,17,Wrigley Field,UN
185594,Zobrist,450314,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,17,Wrigley Field,LF

In [36]:
RE17['Start1'] = np.where(pd.isnull(RE17['start1B']),0,1)
RE17['Start2'] = np.where(pd.isnull(RE17['start2B']),0,1)
RE17['Start3'] = np.where(pd.isnull(RE17['start3B']),0,1)

RE17['Start_State'] = (RE17['Start1'].astype(str) + RE17['Start2'].astype(str) + RE17['Start3'].astype(str)+\
                          " " + RE17['startOuts'].astype(str))

RE17['End1'] = np.where(pd.isnull(RE17['end1B']),0,1)
RE17['End2'] = np.where(pd.isnull(RE17['end2B']),0,1)
RE17['End3'] = np.where(pd.isnull(RE17['end3B']),0,1)

RE17['End_State'] = (RE17['End1'].astype(str) + RE17['End2'].astype(str) + RE17['End3'].astype(str) + \
                        " " + RE17['endOuts'].astype(str))

RE17 = RE17[((RE17.Start_State != RE17.End_State) | (RE17.runsOnPlay > 0)) & (RE17.outsInInning == 3)]

Start_RunExp = RE17.groupby(['Start_State'])['runsFuture'].mean().reset_index().rename(columns={'runsFuture':'Start_RE'})

RE17 = pd.merge(RE17, Start_RunExp, on=['Start_State'], how='left')

Base_State_3 = [pd.Series(['000 3', 0], index=Start_RunExp.columns),
                pd.Series(['001 3', 0], index=Start_RunExp.columns),
                pd.Series(['010 3', 0], index=Start_RunExp.columns),
                pd.Series(['011 3', 0], index=Start_RunExp.columns),
                pd.Series(['100 3', 0], index=Start_RunExp.columns),
                pd.Series(['101 3', 0], index=Start_RunExp.columns),
                pd.Series(['110 3', 0], index=Start_RunExp.columns),
                pd.Series(['111 3', 0], index=Start_RunExp.columns)]
Start_RunExp = Start_RunExp.append(Base_State_3, ignore_index=True)

End_RunExp = Start_RunExp.rename(columns={'Start_State':'End_State', 'Start_RE':'End_RE'})

RE17 = pd.merge(RE17, End_RunExp, on=['End_State'], how='left')

RE17['Run_Value'] = RE17['runsOnPlay'] + RE17['End_RE'] - RE17['Start_RE']

RE17

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,...,Start2,Start3,Start_State,End1,End2,End3,End_State,Start_RE,End_RE,Run_Value
0,Gardner,458731,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.516375,0.272176,-0.244199
1,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.272176,0.108038,-0.164138
2,Bird,595885,Walk,NaN,NaN,NaN,595885.0,NaN,NaN,2,...,0,0,000 2,1,0,0,100 2,0.108038,0.225365,0.117327
3,Holliday,407812,Groundout,595885.0,NaN,NaN,NaN,NaN,NaN,2,...,0,0,100 2,0,0,0,000 3,0.225365,0.000000,-0.225365
4,"Dickerson, C",572816,Single,NaN,NaN,NaN,572816.0,NaN,NaN,0,...,0,0,000 0,1,0,0,100 0,0.516375,0.912921,0.396546
5,Kiermaier,595281,Double,572816.0,NaN,NaN,NaN,595281.0,572816.0,0,...,0,0,100 0,0,1,1,011 0,0.912921,2.051376,1.138455
6,Longoria,446334,Sac Fly,NaN,595281.0,572816.0,NaN,595281.0,NaN,0,...,1,1,011 0,0,1,0,010 1,2.051376,0.711650,-0.339727
7,"Miller, B",543543,Single,NaN,595281.0,NaN,543543.0,NaN,595281.0,1,...,1,0,010 1,1,0,1,101 1,0.711650,1.215306,0.503657
8,Souza Jr.,519306,Walk,543543.0,NaN,595281.0,519306.0,543543.0,595281.0,1,...,0,1,101 1,1,1,1,111 1,1.215306,1.635608,0.420302
9,Morrison,489149,Single,519306.0,543543.0,595281.0,489149.0,519306.0,NaN,1,...,1,1,111 1,1,1,0,110 1,1.635608,0.947424,1.311816
10,Beckham,542921,Lineout,489149.0,519306.0,NaN,489149.0,519306.0,NaN,1,...,1,0,110 1,1,1,0,110 2,0.947424,0.449782,-0.497642
11,"Smith, M",605480,Strikeout,489149.0,519306.0,NaN,NaN,NaN,NaN,2,...,1,0,110 2,0,0,0,000 3,0.449782,0.000000,-0.449782
12,Ellsbury,453056,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.516375,0.272176,-0.244199
13,"Castro, S",516770,Single,NaN,NaN,NaN,516770.0,NaN,NaN,1,...,0,0,000 1,1,0,0,100 1,0.272176,0.524904,0.252728
14,Headley,452104,Single,516770.0,NaN,NaN,452104.0,516770.0,NaN,1,...,0,0,100 1,1,1,0,110 1,0.524904,0.947424,0.422520
15,Judge,592450,Double,452104.0,516770.0,NaN,NaN,592450.0,452104.0,1,...,1,0,110 1,0,1,1,011 1,0.947424,1.517131,1.569707
16,Torreyes,591720,Groundout,NaN,592450.0,452104.0,NaN,NaN,592450.0,1,...,1,1,011 1,0,0,1,001 2,1.517131,0.381186,-0.135945
17,Gardner,458731,Groundout,NaN,NaN,592450.0,NaN,NaN,NaN,2,...,0,1,001 2,0,0,0,000 3,0.381186,0.000000,-0.381186
18,"Norris, De",519083,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.516375,0.272176,-0.244199
19,"Dickerson, C",572816,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.272176,0.108038,-0.164138
20,Kiermaier,595281,Walk,NaN,NaN,NaN,595281.0,NaN,NaN,2,...,0,0,000 2,1,0,0,100 2,0.108038,0.225365,0.117327
21,Longoria,446334,Home Run,595281.0,NaN,NaN,NaN,NaN,NaN,2,...,0,0,100 2,0,0,0,000 2,0.225365,0.108038,1.882673
22,"Miller, B",543543,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,000 2,0,0,0,000 3,0.108038,0.000000,-0.108038
23,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.516375,0.272176,-0.244199
24,Bird,595885,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.272176,0.108038,-0.164138
25,Holliday,407812,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,000 2,0,0,0,000 3,0.108038,0.000000,-0.108038
26,Souza Jr.,519306,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.516375,0.272176,-0.244199
27,Morrison,489149,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 1,0.272176,0.272176,1.000000
28,Beckham,542921,Double,NaN,NaN,NaN,NaN,542921.0,NaN,1,...,0,0,000 1,0,1,0,010 1,0.272176,0.711650,0.439473
29,"Smith, M",605480,Single,NaN,542921.0,NaN,NaN,605480.0,NaN,1,...,1,0,010 1,0,1,0,010 1,0.711650,0.711650,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184721,Duvall,594807,Double,NaN,NaN,NaN,NaN,594807.0,NaN,1,...,0,0,000 1,0,1,0,010 1,0.272176,0.711650,0.439473
184722,Suarez,553993,Single,NaN,594807.0,NaN,553993.0,NaN,594807.0,1,...,1,0,010 1,1,0,1,101 1,0.711650,1.215306,0.503657
184723,Gennett,571697,Single,553993.0,NaN,594807.0,571697.0,553993.0,NaN,1,...,0,1,101 1,1,1,0,110 1,1.215306,0.947424,0.732118
184724,Ervin,640447,Lineout,571697.0,553993.0,NaN,571697.0,553993.0,NaN,1,...,1,0,110 1,1,1,0,110 2,0.947424,0.449782,-0.497642
184725,Wallach,595453,Strikeout,571697.0,553993.0,NaN,NaN,NaN,NaN,2,...,1,0,110 2,0,0,0,000 3,0.449782,0.000000,-0.449782
184726,"Davis, T",543089,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.516375,0.272176,-0.244199
184727,Almora Jr.,546991,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.272176,0.108038,-0.164138
184728,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,000 2,0,0,0,000 3,0.108038,0.000000,-0.108038
184729,Kivlehan,623182,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.516375,0.272176,-0.244199
184730,Hamilton,571740,Lineout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.272176,0.108038,-0.164138
184731,Vincej,572227,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,000 2,0,0,0,000 3,0.108038,0.000000,-0.108038
184732,Zobrist,450314,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.516375,0.272176,-0.244199
184733,"Pena, Fe",570240,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.272176,0.108038,-0.164138
184734,Schwarber,656941,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,000 2,0,0,0,000 3,0.108038,0.000000,-0.108038
184735,Votto,458015,Double,NaN,NaN,NaN,NaN,458015.0,NaN,0,...,0,0,000 0,0,1,0,010 0,0.516375,1.154829,0.638454
184736,Duvall,594807,Strikeout,NaN,458015.0,NaN,NaN,458015.0,NaN,0,...,1,0,010 0,0,1,0,010 1,1.154829,0.711650,-0.443179
184737,Suarez,553993,Flyout,NaN,458015.0,NaN,NaN,458015.0,NaN,1,...,1,0,010 1,0,1,0,010 2,0.711650,0.336702,-0.374947
184738,Gennett,571697,Strikeout,NaN,458015.0,NaN,NaN,NaN,NaN,2,...,1,0,010 2,0,0,0,000 3,0.336702,0.000000,-0.336702
184739,Caratini,605170,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.516375,0.272176,-0.244199
184740,La Stella,600303,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.272176,0.108038,-0.164138
184741,"Happ, I",664023,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,000 2,0,0,0,000 3,0.108038,0.000000,-0.108038
184742,Ervin,640447,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.516375,0.272176,-0.244199
184743,Wallach,595453,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.272176,0.108038,-0.164138
184744,Winker,608385,Single,NaN,NaN,NaN,608385.0,NaN,NaN,2,...,0,0,000 2,1,0,0,100 2,0.108038,0.225365,0.117327
184745,Hamilton,571740,Walk,608385.0,NaN,NaN,571740.0,608385.0,NaN,2,...,0,0,100 2,1,1,0,110 2,0.225365,0.449782,0.224418
184746,Vincej,572227,Runner Out,571740.0,608385.0,NaN,NaN,NaN,NaN,2,...,1,0,110 2,0,0,0,000 3,0.449782,0.000000,-0.449782
184747,"Davis, T",543089,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.516375,0.272176,-0.244199
184748,Almora Jr.,546991,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 1,0.272176,0.272176,1.000000
184749,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.272176,0.108038,-0.164138
184750,Zobrist,450314,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,000 2,0,0,0,000 3,0.108038,0.000000,-0.108038

In [39]:
Event_Value17 = RE17.groupby(['event'])['Run_Value'].mean().reset_index()
Event_Value17 = Event_Value17.rename(columns={'Run_Value':'Run_Value17'})
Event_Value17

                   event  Run_Value17
0    Batter Interference    -0.430019
1         Bunt Groundout    -0.209411
2           Bunt Lineout    -0.328292
3           Bunt Pop Out    -0.373225
4   Catcher Interference     0.399070
5                 Double     0.779338
6            Double Play    -0.897164
7       Fan interference     0.590743
8            Field Error     0.493206
9        Fielders Choice     0.764112
10   Fielders Choice Out    -0.662400
11                Flyout    -0.262548
12              Forceout    -0.345347
13      Grounded Into DP    -0.818005
14             Groundout    -0.224579
15          Hit By Pitch     0.338679
16              Home Run     1.378739
17           Intent Walk     0.180109
18               Lineout    -0.259682
19               Pop Out    -0.283498
20            Runner Out    -0.274991
21              Sac Bunt    -0.109283
22               Sac Fly    -0.032119
23            Sac Fly DP    -0.543715
24                Single     0.455773
25             Strikeout    -0.269985
26        Strikeout - DP    -0.682819
27                Triple     1.063607
28           Triple Play    -1.471223
29                  Walk     0.322635

# II. Coding Run Expectancy Dataset (2016)

In [40]:
# Read in MLBAM Data for 2016

MLBAM16 = pd.read_csv("../Data/MLBAM16.csv")

In [41]:
#Your Code Here
RE16 = MLBAM16[['batterName','batterId','event', 'start1B', 'start2B', 'start3B', 'end1B', 'end2B', 'end3B',\
                   'startOuts','endOuts','runsFuture','runsOnPlay','outsInInning',\
                   'stand', 'throws','venueId', 'stadium', 'batterPos']].copy()

RE16['Start1'] = np.where(pd.isnull(RE16['start1B']),0,1)
RE16['Start2'] = np.where(pd.isnull(RE16['start2B']),0,1)
RE16['Start3'] = np.where(pd.isnull(RE16['start3B']),0,1)

RE16['Start_State'] = (RE16['Start1'].astype(str) + RE16['Start2'].astype(str) + RE16['Start3'].astype(str)+\
                          " " + RE16['startOuts'].astype(str))

RE16['End1'] = np.where(pd.isnull(RE16['end1B']),0,1)
RE16['End2'] = np.where(pd.isnull(RE16['end2B']),0,1)
RE16['End3'] = np.where(pd.isnull(RE16['end3B']),0,1)

RE16['End_State'] = (RE16['End1'].astype(str) + RE16['End2'].astype(str) + RE16['End3'].astype(str) + \
                        " " + RE16['endOuts'].astype(str))

RE16 = RE16[((RE16.Start_State != RE16.End_State) | (RE16.runsOnPlay > 0)) & (RE16.outsInInning == 3)]

Start_RunExp = RE16.groupby(['Start_State'])['runsFuture'].mean().reset_index().rename(columns={'runsFuture':'Start_RE'})

RE16 = pd.merge(RE16, Start_RunExp, on=['Start_State'], how='left')

Base_State_3 = [pd.Series(['000 3', 0], index=Start_RunExp.columns),
                pd.Series(['001 3', 0], index=Start_RunExp.columns),
                pd.Series(['010 3', 0], index=Start_RunExp.columns),
                pd.Series(['011 3', 0], index=Start_RunExp.columns),
                pd.Series(['100 3', 0], index=Start_RunExp.columns),
                pd.Series(['101 3', 0], index=Start_RunExp.columns),
                pd.Series(['110 3', 0], index=Start_RunExp.columns),
                pd.Series(['111 3', 0], index=Start_RunExp.columns)]
Start_RunExp = Start_RunExp.append(Base_State_3, ignore_index=True)

End_RunExp = Start_RunExp.rename(columns={'Start_State':'End_State', 'Start_RE':'End_RE'})

RE16 = pd.merge(RE16, End_RunExp, on=['End_State'], how='left')

RE16['Run_Value'] = RE16['runsOnPlay'] + RE16['End_RE'] - RE16['Start_RE']

RE16

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,...,Start2,Start3,Start_State,End1,End2,End3,End_State,Start_RE,End_RE,Run_Value
0,"Carpenter, M",572761,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.498377,0.268678,-0.229699
1,Pham,502054,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.268678,0.106305,-0.162373
2,Holliday,407812,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,000 2,0,0,0,000 3,0.106305,0.000000,-0.106305
3,Jaso,444379,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.498377,0.268678,-0.229699
4,McCutchen,457705,Hit By Pitch,NaN,NaN,NaN,457705.0,NaN,NaN,1,...,0,0,000 1,1,0,0,100 1,0.268678,0.512225,0.243547
5,Freese,501896,Single,457705.0,NaN,NaN,501896.0,NaN,457705.0,1,...,0,0,100 1,1,0,1,101 1,0.512225,1.196777,0.684552
6,"Marte, S",516782,Lineout,501896.0,NaN,457705.0,501896.0,NaN,457705.0,1,...,0,1,101 1,1,0,1,101 2,1.196777,0.480175,-0.716603
7,Cervelli,465041,Pop Out,501896.0,NaN,457705.0,NaN,NaN,NaN,2,...,0,1,101 2,0,0,0,000 3,0.480175,0.000000,-0.480175
8,Grichuk,545341,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.498377,0.268678,-0.229699
9,Piscotty,572039,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.268678,0.106305,-0.162373
10,Molina,425877,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,000 2,0,0,0,000 3,0.106305,0.000000,-0.106305
11,"Polanco, G",570256,Double,NaN,NaN,NaN,NaN,570256.0,NaN,0,...,0,0,000 0,0,1,0,010 0,0.498377,1.132468,0.634090
12,Harrison,543281,Groundout,NaN,570256.0,NaN,NaN,NaN,570256.0,0,...,1,0,010 0,0,0,1,001 1,1.132468,0.948684,-0.183783
13,Mercer,474568,Walk,NaN,NaN,570256.0,474568.0,NaN,570256.0,1,...,0,1,001 1,1,0,1,101 1,0.948684,1.196777,0.248093
14,Liriano,434538,Single,474568.0,NaN,570256.0,434538.0,474568.0,NaN,1,...,0,1,101 1,1,1,0,110 1,1.196777,0.922572,0.725795
15,Jaso,444379,Single,434538.0,474568.0,NaN,444379.0,434538.0,NaN,1,...,1,0,110 1,1,1,0,110 1,0.922572,0.922572,1.000000
16,McCutchen,457705,Flyout,444379.0,434538.0,NaN,444379.0,434538.0,NaN,1,...,1,0,110 1,1,1,0,110 2,0.922572,0.414466,-0.508107
17,Freese,501896,Groundout,444379.0,434538.0,NaN,NaN,NaN,NaN,2,...,1,0,110 2,0,0,0,000 3,0.414466,0.000000,-0.414466
18,Wong,543939,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.498377,0.268678,-0.229699
19,Gyorko,576397,Walk,NaN,NaN,NaN,576397.0,NaN,NaN,1,...,0,0,000 1,1,0,0,100 1,0.268678,0.512225,0.243547
20,Wainwright,425794,Field Error,576397.0,NaN,NaN,425794.0,NaN,576397.0,1,...,0,0,100 1,1,0,1,101 1,0.512225,1.196777,0.684552
21,"Carpenter, M",572761,Grounded Into DP,425794.0,NaN,576397.0,NaN,NaN,NaN,1,...,0,1,101 1,0,0,0,000 3,1.196777,0.000000,-1.196777
22,"Marte, S",516782,Lineout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.498377,0.268678,-0.229699
23,Cervelli,465041,Walk,NaN,NaN,NaN,465041.0,NaN,NaN,1,...,0,0,000 1,1,0,0,100 1,0.268678,0.512225,0.243547
24,"Polanco, G",570256,Flyout,465041.0,NaN,NaN,465041.0,NaN,NaN,1,...,0,0,100 1,1,0,0,100 2,0.512225,0.220539,-0.291686
25,Harrison,543281,Strikeout,465041.0,NaN,NaN,NaN,NaN,NaN,2,...,0,0,100 2,0,0,0,000 3,0.220539,0.000000,-0.220539
26,Adams,571431,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.498377,0.268678,-0.229699
27,Holliday,407812,Single,NaN,NaN,NaN,407812.0,NaN,NaN,1,...,0,0,000 1,1,0,0,100 1,0.268678,0.512225,0.243547
28,Grichuk,545341,Single,407812.0,NaN,NaN,545341.0,407812.0,NaN,1,...,0,0,100 1,1,1,0,110 1,0.512225,0.922572,0.410347
29,Piscotty,572039,Strikeout,545341.0,407812.0,NaN,545341.0,407812.0,NaN,1,...,1,0,110 1,1,1,0,110 2,0.922572,0.414466,-0.508107
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184122,Grichuk,545341,Strikeout,576397.0,NaN,NaN,576397.0,NaN,NaN,1,...,0,0,100 1,1,0,0,100 2,0.512225,0.220539,-0.291686
184123,"Martinez, Jo",500874,Single,576397.0,NaN,NaN,500874.0,576397.0,NaN,2,...,0,0,100 2,1,1,0,110 2,0.220539,0.414466,0.193926
184124,"Carpenter, M",572761,Home Run,500874.0,576397.0,NaN,NaN,NaN,NaN,2,...,1,0,110 2,0,0,0,000 2,0.414466,0.106305,2.691840
184125,"Diaz, A",649557,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,000 2,0,0,0,000 3,0.106305,0.000000,-0.106305
184126,"Frazier, A",624428,Single,NaN,NaN,NaN,624428.0,NaN,NaN,0,...,0,0,000 0,1,0,0,100 0,0.498377,0.858504,0.360127
184127,Jaso,444379,Home Run,624428.0,NaN,NaN,NaN,NaN,NaN,0,...,0,0,100 0,0,0,0,000 0,0.858504,0.498377,1.639873
184128,"Polanco, G",570256,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.498377,0.268678,-0.229699
184129,McCutchen,457705,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.268678,0.106305,-0.162373
184130,Kang,628356,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,000 2,0,0,0,000 3,0.106305,0.000000,-0.106305
184131,Molina,425877,Double,NaN,NaN,NaN,NaN,425877.0,NaN,0,...,0,0,000 0,0,1,0,010 0,0.498377,1.132468,0.634090
184132,Piscotty,572039,Single,NaN,425877.0,NaN,572039.0,NaN,NaN,0,...,1,0,010 0,1,0,0,100 0,1.132468,0.858504,0.726037
184133,"Peralta, J",425509,Single,572039.0,NaN,NaN,425509.0,572039.0,NaN,0,...,0,0,100 0,1,1,0,110 0,0.858504,1.447597,0.589092
184134,Moss,461235,Single,425509.0,572039.0,NaN,461235.0,425509.0,572039.0,0,...,1,0,110 0,1,1,1,111 0,1.447597,2.112409,0.664812
184135,Gyorko,576397,Field Error,461235.0,425509.0,572039.0,576397.0,461235.0,425509.0,0,...,1,1,111 0,1,1,1,111 0,2.112409,2.112409,1.000000
184136,Grichuk,545341,Double,576397.0,461235.0,425509.0,NaN,545341.0,576397.0,0,...,1,1,111 0,0,1,1,011 0,2.112409,1.916190,1.803782
184137,Adams,571431,Sac Fly,NaN,545341.0,576397.0,NaN,NaN,545341.0,0,...,1,1,011 0,0,0,1,001 1,1.916190,0.948684,0.032494
184138,"Carpenter, M",572761,Sac Fly,NaN,NaN,545341.0,NaN,NaN,NaN,1,...,0,1,001 1,0,0,0,000 2,0.948684,0.106305,0.157621
184139,"Diaz, A",649557,Pop Out,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,000 2,0,0,0,000 3,0.106305,0.000000,-0.106305
184140,Joyce,459964,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.498377,0.268678,-0.229699
184141,Hanson,593700,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.268678,0.106305,-0.162373
184142,Fryer,518700,Single,NaN,NaN,NaN,518700.0,NaN,NaN,2,...,0,0,000 2,1,0,0,100 2,0.106305,0.220539,0.114234
184143,Florimon,465753,Groundout,518700.0,NaN,NaN,NaN,NaN,NaN,2,...,0,0,100 2,0,0,0,000 3,0.220539,0.000000,-0.220539
184144,Molina,425877,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.498377,0.268678,-0.229699
184145,Piscotty,572039,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.268678,0.106305,-0.162373
184146,"Garcia, G",594824,Single,NaN,NaN,NaN,594824.0,NaN,NaN,2,...,0,0,000 2,1,0,0,100 2,0.106305,0.220539,0.114234
184147,Moss,461235,Strikeout,594824.0,NaN,NaN,NaN,NaN,NaN,2,...,0,0,100 2,0,0,0,000 3,0.220539,0.000000,-0.220539
184148,"Rogers, J",595386,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.498377,0.268678,-0.229699
184149,Jaso,444379,Walk,NaN,NaN,NaN,444379.0,NaN,NaN,1,...,0,0,000 1,1,0,0,100 1,0.268678,0.512225,0.243547
184150,"Polanco, G",570256,Strikeout,444379.0,NaN,NaN,444379.0,NaN,NaN,1,...,0,0,100 1,1,0,0,100 2,0.512225,0.220539,-0.291686
184151,McCutchen,457705,Groundout,444379.0,NaN,NaN,NaN,NaN,NaN,2,...,0,0,100 2,0,0,0,000 3,0.220539,0.000000,-0.220539

In [42]:
Event_Value16 = RE16.groupby(['event'])['Run_Value'].mean().reset_index()
Event_Value16 = Event_Value16.rename(columns={'Run_Value':'Run_Value16'})
Event_Value16

                   event  Run_Value16
0    Batter Interference    -0.284649
1         Bunt Groundout    -0.218826
2           Bunt Lineout    -0.352295
3           Bunt Pop Out    -0.342802
4   Catcher Interference     0.301623
5                 Double     0.743467
6            Double Play    -0.864981
7       Fan interference     0.533316
8            Field Error     0.469989
9        Fielders Choice     0.701447
10   Fielders Choice Out    -0.610757
11                Flyout    -0.247896
12              Forceout    -0.326657
13      Grounded Into DP    -0.773318
14             Groundout    -0.212992
15          Hit By Pitch     0.320569
16              Home Run     1.382476
17           Intent Walk     0.172551
18               Lineout    -0.248542
19               Pop Out    -0.267062
20            Runner Out    -0.257904
21              Sac Bunt    -0.126691
22               Sac Fly     0.023233
23            Sac Fly DP    -0.370443
24     Sacrifice Bunt DP    -0.752199
25                Single     0.440258
26             Strikeout    -0.259940
27        Strikeout - DP    -0.622787
28                Triple     1.023911
29           Triple Play    -1.637543
30                  Walk     0.299404

# III. Comparing 2016 vs. 2017

In [43]:
#Your Code Here
Event_1617 = pd.merge(Event_Value16,Event_Value17,on=['event'])
Event_1617

                   event  Run_Value16  Run_Value17
0    Batter Interference    -0.284649    -0.430019
1         Bunt Groundout    -0.218826    -0.209411
2           Bunt Lineout    -0.352295    -0.328292
3           Bunt Pop Out    -0.342802    -0.373225
4   Catcher Interference     0.301623     0.399070
5                 Double     0.743467     0.779338
6            Double Play    -0.864981    -0.897164
7       Fan interference     0.533316     0.590743
8            Field Error     0.469989     0.493206
9        Fielders Choice     0.701447     0.764112
10   Fielders Choice Out    -0.610757    -0.662400
11                Flyout    -0.247896    -0.262548
12              Forceout    -0.326657    -0.345347
13      Grounded Into DP    -0.773318    -0.818005
14             Groundout    -0.212992    -0.224579
15          Hit By Pitch     0.320569     0.338679
16              Home Run     1.382476     1.378739
17           Intent Walk     0.172551     0.180109
18               Lineout    -0.248542    -0.259682
19               Pop Out    -0.267062    -0.283498
20            Runner Out    -0.257904    -0.274991
21              Sac Bunt    -0.126691    -0.109283
22               Sac Fly     0.023233    -0.032119
23            Sac Fly DP    -0.370443    -0.543715
24                Single     0.440258     0.455773
25             Strikeout    -0.259940    -0.269985
26        Strikeout - DP    -0.622787    -0.682819
27                Triple     1.023911     1.063607
28           Triple Play    -1.637543    -1.471223
29                  Walk     0.299404     0.322635

In [51]:
Event_1617['diff'] = Event_1617['Run_Value17'] - Event_1617['Run_Value16']
Event_1617.sort_values(by='diff')

                   event  Run_Value16  Run_Value17      diff
23            Sac Fly DP    -0.370443    -0.543715 -0.173272
0    Batter Interference    -0.284649    -0.430019 -0.145369
26        Strikeout - DP    -0.622787    -0.682819 -0.060032
22               Sac Fly     0.023233    -0.032119 -0.055352
10   Fielders Choice Out    -0.610757    -0.662400 -0.051643
13      Grounded Into DP    -0.773318    -0.818005 -0.044687
6            Double Play    -0.864981    -0.897164 -0.032183
3           Bunt Pop Out    -0.342802    -0.373225 -0.030423
12              Forceout    -0.326657    -0.345347 -0.018691
20            Runner Out    -0.257904    -0.274991 -0.017087
19               Pop Out    -0.267062    -0.283498 -0.016436
11                Flyout    -0.247896    -0.262548 -0.014652
14             Groundout    -0.212992    -0.224579 -0.011588
18               Lineout    -0.248542    -0.259682 -0.011140
25             Strikeout    -0.259940    -0.269985 -0.010045
16              Home Run     1.382476     1.378739 -0.003737
17           Intent Walk     0.172551     0.180109  0.007558
1         Bunt Groundout    -0.218826    -0.209411  0.009415
24                Single     0.440258     0.455773  0.015515
21              Sac Bunt    -0.126691    -0.109283  0.017409
15          Hit By Pitch     0.320569     0.338679  0.018110
8            Field Error     0.469989     0.493206  0.023217
29                  Walk     0.299404     0.322635  0.023231
2           Bunt Lineout    -0.352295    -0.328292  0.024003
5                 Double     0.743467     0.779338  0.035870
27                Triple     1.023911     1.063607  0.039695
7       Fan interference     0.533316     0.590743  0.057427
9        Fielders Choice     0.701447     0.764112  0.062665
4   Catcher Interference     0.301623     0.399070  0.097447
28           Triple Play    -1.637543    -1.471223  0.166319

In [47]:
Player_Value16 = RE16.groupby(['batterName'])['Run_Value'].sum().reset_index()
Player_Value16 = Player_Value16.rename(columns={'Run_Value':'Run_Value16'})
# Player_Value16 = Player_Value16.sort_values(by=['Run_Value'],  ascending=False) 
Player_Value17 = RE17.groupby(['batterName'])['Run_Value'].sum().reset_index()
Player_Value17 = Player_Value17.rename(columns={'Run_Value':'Run_Value17'})
# Player_Value17 = Player_Value17.sort_values(by=['Run_Value'],  ascending=False)
Player_1617 = pd.merge(Player_Value16,Player_Value17,on=['batterName'])

In [49]:
Player_1617.sort_values(by='Run_Value16',ascending=True)

      batterName  Run_Value16  Run_Value17
269  Hechavarria   -32.142529    -6.378460
440   Norris, De   -26.841250   -11.798153
171   Escobar, A   -26.555530   -22.348618
78         Burns   -23.335961    -1.429560
6          Ahmed   -23.000581    -4.176089
683    Zimmerman   -22.942623    33.179676
201       Galvis   -22.751256   -13.695274
370     Marte, K   -21.742476    -3.503534
296  Iglesias, J   -21.271729   -11.173195
309   Joseph, Ca   -20.085234    -8.346937
511       Revere   -19.493233    -6.619925
358      Mahtook   -18.597420    -1.184826
372    Martin, L   -17.784503   -13.139457
282      Heyward   -17.099341     2.479838
32        Aviles   -16.951381    -6.077192
184    Flores, R   -16.733862    -1.172803
230  Gonzalez, M   -16.649256    35.951866
585    Smolinski   -16.406132    -2.443034
329        Kratz   -16.389089     1.892890
224        Gomes   -16.172017    -6.767861
454        Parra   -15.948345    12.319789
132        Cueto   -15.836621   -10.643992
579      Simmons   -15.754664    -1.742177
302    Jankowski   -15.612078    -9.545011
222        Goins   -15.580144    -5.032530
119        Colon   -15.380841    -6.053060
386       McCann   -15.379222    -1.999418
365    Marisnick   -15.271764     1.176953
255     Hamilton   -15.101036   -30.668233
557   Santana, D   -14.330371    -0.480378
..           ...          ...          ...
46          Belt    27.272456     7.753233
426        Myers    27.423018     3.708292
556   Santana, C    27.831142    19.651084
70         Braun    27.845791     4.101122
91          Cano    28.497452    26.869401
227  Gonzalez, C    28.576921    -5.394397
572       Segura    28.717694    -5.523280
569    Seager, C    28.741630    26.499725
48        Beltre    29.745115    27.205050
498   Ramirez, H    30.676190   -19.461039
263       Harper    30.806830    37.730864
131         Cruz    30.882125    46.105828
339     LeMahieu    31.058310     1.844428
355      Machado    31.742868     1.759563
56      Blackmon    33.411154    62.032793
14        Altuve    34.657744    36.862616
223  Goldschmidt    36.197730    56.078941
170  Encarnacion    36.225266    21.707405
54         Betts    36.363718    25.043520
82       Cabrera    37.520249    -4.336300
639       Turner    39.048572    18.814733
520        Rizzo    43.080606    37.865377
194      Freeman    45.551348    24.477837
657        Votto    45.883627    67.650742
74        Bryant    47.832680    34.845708
422    Murphy, D    48.234104    37.079417
154    Donaldson    48.510824    32.587402
25       Arenado    48.979171    56.111576
449        Ortiz    60.938730    -2.629789
636        Trout    68.143360    50.431739

[691 rows x 3 columns]

In [52]:
Player_1617['diff'] = Player_1617['Run_Value17'] - Player_1617['Run_Value16']
Player_1617.sort_values(by='diff')

       batterName  Run_Value16  Run_Value17       diff
449         Ortiz    60.938730    -2.629789 -63.568519
498    Ramirez, H    30.676190   -19.461039 -50.137229
444          Odor    11.679587   -36.464351 -48.143938
82        Cabrera    37.520249    -4.336300 -41.856549
637        Trumbo    21.644283   -17.990412 -39.634695
47        Beltran    21.279393   -16.883042 -38.162435
384        Maybin    23.263283   -12.318532 -35.581815
572        Segura    28.717694    -5.523280 -34.240974
227   Gonzalez, C    28.576921    -5.394397 -33.971317
160        Duvall    21.819293   -11.639746 -33.459040
685       Zobrist    18.888483   -13.718812 -32.607296
324       Kinsler    21.481252   -10.076064 -31.557316
43       Bautista    15.171797   -15.256682 -30.428479
355       Machado    31.742868     1.759563 -29.983305
148       Diaz, A    16.695314   -12.989348 -29.684661
527  Rodriguez, S    14.448815   -15.182604 -29.631419
495        Pujols    15.581010   -13.892055 -29.473065
339      LeMahieu    31.058310     1.844428 -29.213882
190        Franco     9.611410   -19.115330 -28.726740
483       Plouffe    -0.725095   -29.004223 -28.279128
481      Piscotty    24.063534    -3.609730 -27.673263
484    Polanco, G    10.610631   -15.892235 -26.502865
546      Saladino    -3.574239   -29.484769 -25.910531
587       Solarte    22.286786    -3.617288 -25.904074
226   Gonzalez, A    18.186314    -7.670641 -25.856956
325        Kipnis    24.175581    -1.279526 -25.455107
668       Wieters     6.150161   -18.729529 -24.879690
70          Braun    27.845791     4.101122 -23.744669
426         Myers    27.423018     3.708292 -23.714726
379   Martinez, V     7.335464   -16.021087 -23.356552
..            ...          ...          ...        ...
78          Burns   -23.335961    -1.429560  21.906401
200         Gallo    -4.786957    17.459019  22.245976
623     Taylor, C    -2.211697    20.588698  22.800395
509        Rendon    18.235958    41.422600  23.186642
590     Souza Jr.    -4.894369    18.886509  23.780878
295      Iannetta   -10.007643    14.045915  24.053558
243     Gregorius    -3.591038    20.475311  24.066349
640         Upton    10.642522    35.833621  25.191098
12         Alonso    -6.983720    18.374849  25.358569
269   Hechavarria   -32.142529    -6.378460  25.764069
250       Gurriel    -4.873403    22.053024  26.926427
506       Reddick     2.184347    29.449762  27.265415
283      Hicks, A   -13.219054    14.428142  27.647196
123     Contreras    -0.530910    27.219171  27.750081
454         Parra   -15.948345    12.319789  28.268134
382         Mauer     3.738712    32.012389  28.273677
56       Blackmon    33.411154    62.032793  28.621639
350        Lowrie   -12.914838    16.438851  29.353689
343          Lind   -12.359832    20.276339  32.636172
472          Pham    -1.695485    31.204334  32.899819
205    Garcia, Av     0.792947    34.612266  33.819319
583         Smoak   -12.844614    22.263561  35.108175
128        Cozart    -2.402277    33.761590  36.163867
215       Gennett    -8.970409    29.352662  38.323071
451         Ozuna     7.040069    45.648106  38.608037
121      Conforto    -3.607318    35.827160  39.434477
595       Stanton    10.070038    51.784088  41.714049
230   Gonzalez, M   -16.649256    35.951866  52.601121
683     Zimmerman   -22.942623    33.179676  56.122300
312         Judge    -4.179157    57.081625  61.260782

[691 rows x 4 columns]