# I. Data Coding and Merging

In [1]:
# Load packages
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# Load game logs data
Teams = pd.read_excel("../Data/Game logs 1999-2003.xlsx")

In [3]:
#Your Code Here
Teams['hwin'] = np.where(Teams['home_score'] > Teams['visitor_score'],1,0)
Teams['awin'] = np.where(Teams['home_score'] < Teams['visitor_score'],1,0)

In [4]:
Teams['year'] = Teams['date'].astype(str).str[0:4]
Teams

,date,game_number,day,visitor,visitor_lg,visitor_game_number,home,home_lg,home_game_number,visitor_score,...,home_batter_8_name,home_batter_8_pos,home_batter_9_id,home_batter_9_name,home_batter_9_pos,additional_info,acquisition,hwin,awin,year
0,19990404,0,Sun,COL,NL,1,SDN,NL,1,8,...,Chris Gomez,6,ashba002,Andy Ashby,1,NaN,Y,0,1,1999
1,19990405,0,Mon,TBA,AL,1,BAL,AL,1,7,...,Charles Johnson,2,reboj001,Jeff Reboulet,4,NaN,Y,1,0,1999
2,19990405,0,Mon,BOS,AL,1,KCA,AL,1,5,...,Rey Sanchez,6,feblc001,Carlos Febles,4,NaN,Y,0,1,1999
3,19990405,0,Mon,NYA,AL,1,OAK,AL,1,3,...,A.J. Hinch,2,tejam001,Miguel Tejada,6,NaN,Y,1,0,1999
4,19990405,0,Mon,CHA,AL,1,SEA,AL,1,8,...,Russ Davis,5,wilsd001,Dan Wilson,2,NaN,Y,0,1,1999
5,19990405,0,Mon,DET,AL,1,TEX,AL,1,11,...,Todd Zeile,5,clayr001,Royce Clayton,6,NaN,Y,0,1,1999
6,19990405,0,Mon,PHI,NL,1,ATL,NL,1,7,...,Walt Weiss,6,glavt001,Tom Glavine,1,NaN,Y,0,1,1999
7,19990405,0,Mon,SFN,NL,1,CIN,NL,1,11,...,Pokey Reese,4,tomkb001,Brett Tomko,1,NaN,Y,0,1,1999
8,19990405,0,Mon,NYN,NL,1,FLO,NL,1,2,...,Mike Redmond,2,ferna001,Alex Fernandez,1,NaN,Y,1,0,1999
9,19990405,0,Mon,ARI,NL,1,LAN,NL,1,6,...,Adrian Beltre,5,browk001,Kevin Brown,1,NaN,Y,1,0,1999
10,19990405,0,Mon,MON,NL,1,PIT,NL,1,9,...,Mike Benjamin,6,cordf001,Francisco Cordova,1,NaN,Y,0,1,1999
11,19990405,0,Mon,MIL,NL,1,SLN,NL,1,10,...,Placido Polanco,4,osbod001,Donovan Osborne,1,NaN,Y,0,1,1999
12,19990406,0,Tue,CLE,AL,1,ANA,AL,1,5,...,Matt Walbeck,2,sheea001,Andy Sheets,6,NaN,Y,1,0,1999
13,19990406,0,Tue,TOR,AL,1,MIN,AL,1,1,...,Terry Steinbach,2,guzmc001,Cristian Guzman,6,NaN,Y,1,0,1999
14,19990406,0,Tue,NYA,AL,2,OAK,AL,2,7,...,A.J. Hinch,2,tejam001,Miguel Tejada,6,NaN,Y,0,1,1999
15,19990406,0,Tue,CHA,AL,2,SEA,AL,2,11,...,Butch Huskey,7,lampt001,Tom Lampkin,2,NaN,Y,0,1,1999
16,19990406,0,Tue,DET,AL,2,TEX,AL,2,0,...,Lee Stevens,3,alicl001,Luis Alicea,4,NaN,Y,1,0,1999
17,19990406,0,Tue,PHI,NL,2,ATL,NL,2,3,...,Walt Weiss,6,maddg002,Greg Maddux,1,NaN,Y,1,0,1999
18,19990406,0,Tue,SFN,NL,2,CIN,NL,2,7,...,Pokey Reese,4,berej002,Jason Bere,1,NaN,Y,0,1,1999
19,19990406,0,Tue,NYN,NL,2,FLO,NL,2,12,...,Jorge Fabregas,2,hernl003,Livan Hernandez,1,NaN,Y,0,1,1999
20,19990406,0,Tue,CHN,NL,1,HOU,NL,1,2,...,Ricky Gutierrez,6,reyns001,Shane Reynolds,1,NaN,Y,1,0,1999
21,19990406,0,Tue,ARI,NL,2,LAN,NL,2,2,...,Adrian Beltre,5,parkc002,Chan Ho Park,1,NaN,Y,1,0,1999
22,19990406,0,Tue,MON,NL,2,PIT,NL,2,2,...,Mike Benjamin,6,schmj001,Jason Schmidt,1,NaN,Y,1,0,1999
23,19990406,0,Tue,COL,NL,2,SDN,NL,2,3,...,Chris Gomez,6,hitcs001,Sterling Hitchcock,1,NaN,Y,1,0,1999
24,19990407,0,Wed,CLE,AL,2,ANA,AL,2,9,...,Matt Walbeck,2,sheea001,Andy Sheets,6,NaN,Y,0,1,1999
25,19990407,0,Wed,TBA,AL,2,BAL,AL,2,8,...,Willis Otanez,5,reboj001,Jeff Reboulet,4,NaN,Y,0,1,1999
26,19990407,0,Wed,BOS,AL,2,KCA,AL,2,6,...,Rey Sanchez,6,feblc001,Carlos Febles,4,NaN,Y,0,1,1999
27,19990407,0,Wed,TOR,AL,2,MIN,AL,2,9,...,Terry Steinbach,2,guzmc001,Cristian Guzman,6,NaN,Y,0,1,1999
28,19990407,0,Wed,NYA,AL,3,OAK,AL,3,4,...,A.J. Hinch,2,tejam001,Miguel Tejada,6,NaN,Y,0,1,1999
29,19990407,0,Wed,CHA,AL,3,SEA,AL,3,3,...,Russ Davis,5,wilsd001,Dan Wilson,2,NaN,Y,1,0,1999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12112,20030927,0,Sat,CHA,AL,161,KCA,AL,161,19,...,Desi Relaford,4,difem001,Mike Difelice,2,NaN,Y,0,1,2003
12113,20030927,0,Sat,BAL,AL,162,NYA,AL,162,2,...,Aaron Boone,5,rivej001,Juan Rivera,9,NaN,Y,1,0,2003
12114,20030927,0,Sat,OAK,AL,161,SEA,AL,161,4,...,Willie Bloomquist,5,wilsd001,Dan Wilson,2,NaN,Y,1,0,2003
12115,20030927,0,Sat,BOS,AL,161,TBA,AL,161,4,...,Toby Hall,2,lafop001,Pete LaForest,10,NaN,Y,1,0,2003
12116,20030927,0,Sat,CLE,AL,161,TOR,AL,161,4,...,Orlando Hudson,4,cashk001,Kevin Cash,2,NaN,Y,1,0,2003
12117,20030927,0,Sat,SLN,NL,161,ARI,NL,161,3,...,Robby Hammock,2,capuc001,Chris Capuano,1,NaN,Y,0,1,2003
12118,20030927,1,Sat,PIT,NL,160,CHN,NL,160,2,...,Damian Miller,2,priom001,Mark Prior,1,NaN,Y,1,0,2003
12119,20030927,2,Sat,PIT,NL,161,CHN,NL,161,2,...,Paul Bako,2,clemm001,Matt Clement,1,NaN,Y,1,0,2003
12120,20030927,0,Sat,MON,NL,161,CIN,NL,161,2,...,Corky Miller,2,reitb001,Brian Reith,1,NaN,Y,1,0,2003
12121,20030927,0,Sat,NYN,NL,160,FLO,NL,161,9,...,Andy Fox,4,redmm002,Mark Redman,1,NaN,Y,0,1,2003
12122,20030927,0,Sat,MIL,NL,161,HOU,NL,161,5,...,Adam Everett,6,villr001,Ron Villone,1,NaN,Y,0,1,2003
12123,20030927,0,Sat,ATL,NL,161,PHI,NL,161,6,...,Tomas Perez,5,telea001,Amaury Telemaco,1,NaN,Y,1,0,2003
12124,20030927,0,Sat,COL,NL,161,SDN,NL,161,10,...,Humberto Quintero,2,bynum001,Mike Bynum,1,NaN,Y,0,1,2003
12125,20030927,1,Sat,LAN,NL,160,SFN,NL,159,5,...,Neifi Perez,6,willj003,Jerome Williams,1,NaN,Y,0,1,2003
12126,20030927,2,Sat,LAN,NL,161,SFN,NL,160,3,...,Yorvit Torrealba,2,hermd001,Dustin Hermanson,1,NaN,Y,1,0,2003
12127,20030928,0,Sun,TEX,AL,162,ANA,AL,162,1,...,Trent Durrington,4,wessb001,Barry Wesson,7,NaN,Y,1,0,2003
12128,20030928,0,Sun,MIN,AL,162,DET,AL,162,4,...,Brandon Inge,2,santr002,Ramon Santiago,6,NaN,Y,1,0,2003
12129,20030928,0,Sun,CHA,AL,162,KCA,AL,162,5,...,Desi Relaford,4,maynb001,Brent Mayne,2,NaN,Y,0,1,2003
12130,20030928,0,Sun,BAL,AL,163,NYA,AL,163,1,...,John Flaherty,2,hensd001,Drew Henson,5,NaN,Y,1,0,2003
12131,20030928,0,Sun,OAK,AL,162,SEA,AL,162,3,...,Mark McLemore,6,wilsd001,Dan Wilson,2,NaN,Y,1,0,2003
12132,20030928,0,Sun,BOS,AL,162,TBA,AL,162,1,...,Toby Hall,2,shumt001,Terry Shumpert,10,NaN,Y,1,0,2003
12133,20030928,0,Sun,CLE,AL,162,TOR,AL,162,2,...,Orlando Hudson,4,cashk001,Kevin Cash,2,NaN,Y,1,0,2003
12134,20030928,0,Sun,SLN,NL,162,ARI,NL,162,9,...,Robby Hammock,2,webbb001,Brandon Webb,1,NaN,Y,0,1,2003
12135,20030928,0,Sun,PIT,NL,162,CHN,NL,162,3,...,Josh Paul,2,mitrs001,Sergio Mitre,1,NaN,Y,0,1,2003
12136,20030928,0,Sun,MON,NL,162,CIN,NL,162,2,...,Tim Hummel,5,rands002,Scott Randall,1,NaN,Y,0,1,2003
12137,20030928,0,Sun,NYN,NL,161,FLO,NL,162,0,...,Mike Redmond,2,willd003,Dontrelle Willis,1,NaN,Y,1,0,2003
12138,20030928,0,Sun,MIL,NL,162,HOU,NL,162,5,...,Adam Everett,6,saark001,Kirk Saarloos,1,NaN,Y,1,0,2003
12139,20030928,0,Sun,ATL,NL,162,PHI,NL,162,5,...,Tomas Perez,5,millk004,Kevin Millwood,1,NaN,Y,0,1,2003
12140,20030928,0,Sun,COL,NL,162,SDN,NL,162,10,...,Gary Bennett,2,peavj001,Jake Peavy,1,NaN,Y,0,1,2003
12141,20030928,0,Sun,LAN,NL,162,SFN,NL,161,3,...,Yorvit Torrealba,2,corrk001,Kevin Correia,1,NaN,Y,1,0,2003

In [5]:
Teamshome = Teams.groupby(['home','year'])['visitor_ab', 'visitor_h','home_ab', 'home_h', 'hwin','awin'].sum()
Teamshome = Teamshome.reset_index()
Teamshome = Teamshome.rename(columns = {"home": "Team"}) 
Teamshome

    Team  year  visitor_ab  visitor_h  home_ab  home_h  hwin  awin
0    ANA  1999        2832        762     2666     669    37    44
1    ANA  2000        2867        800     2742     788    46    35
2    ANA  2001        2873        772     2736     731    39    42
3    ANA  2002        2799        685     2757     769    54    27
4    ANA  2003        2868        743     2685     717    45    37
5    ARI  1999        2814        693     2730     754    52    29
6    ARI  2000        2800        733     2729     763    47    34
7    ARI  2001        2804        720     2709     757    48    33
8    ARI  2002        2859        710     2709     769    55    26
9    ARI  2003        2817        710     2725     752    45    36
10   ATL  1999        2798        674     2668     704    56    25
11   ATL  2000        2833        732     2666     746    51    30
12   ATL  2001        2774        704     2682     702    40    41
13   ATL  2002        2762        659     2646     696    52    28
14   ATL  2003        2790        693     2725     779    55    26
15   BAL  1999        2827        760     2732     762    41    40
16   BAL  2000        2831        735     2653     722    44    37
17   BAL  2001        2823        733     2602     630    30    50
18   BAL  2002        2848        736     2702     671    34    47
19   BAL  2003        2871        759     2766     761    40    40
20   BOS  1999        2820        722     2722     793    49    32
21   BOS  2000        2879        773     2741     754    42    39
22   BOS  2001        2857        725     2772     759    41    40
23   BOS  2002        2800        712     2713     741    42    39
24   BOS  2003        2895        756     2845     899    53    28
25   CHA  1999        2934        826     2726     740    38    42
26   CHA  2000        2830        756     2737     802    46    35
27   CHA  2001        2841        750     2705     731    46    35
28   CHA  2002        2756        703     2678     750    47    34
29   CHA  2003        2757        684     2641     696    51    30
..   ...   ...         ...        ...      ...     ...   ...   ...
120  SEA  1999        2888        828     2721     742    43    38
121  SEA  2000        2810        696     2625     650    47    34
122  SEA  2001        2753        612     2715     769    57    24
123  SEA  2002        2806        709     2689     711    48    33
124  SEA  2003        2738        649     2674     707    50    31
125  SFN  1999        2845        705     2683     703    49    32
126  SFN  2000        2726        682     2652     751    55    26
127  SFN  2001        2832        710     2705     692    49    32
128  SFN  2002        2742        674     2629     681    50    31
129  SFN  2003        2797        692     2704     751    57    24
130  SLN  1999        2866        772     2731     711    38    42
131  SLN  2000        2744        692     2654     717    50    31
132  SLN  2001        2758        668     2675     759    54    28
133  SLN  2002        2762        662     2684     715    52    29
134  SLN  2003        2857        729     2758     799    48    33
135  TBA  1999        2892        839     2700     722    33    48
136  TBA  2000        2894        801     2669     675    36    44
137  TBA  2001        2868        775     2727     727    37    44
138  TBA  2002        2904        772     2825     749    30    51
139  TBA  2003        2839        735     2795     752    36    45
140  TEX  1999        2928        846     2756     837    51    30
141  TEX  2000        2943        848     2780     821    42    39
142  TEX  2001        2995        869     2820     798    41    41
143  TEX  2002        2906        815     2756     782    42    39
144  TEX  2003        2929        855     2787     798    43    38
145  TOR  1999        2891        817     2731     765    40    41
146  TOR  2000        2910        819     2766     768    45    36
147  TOR  2001        2911        800     2809     757    40    42
148  TOR  2002        2838        749     2729     734    42    39
149  TOR  2003        2930        827     2763     779    41    40

[150 rows x 8 columns]

In [6]:
Teamsaway = Teams.groupby(['visitor','year'])['visitor_ab', 'visitor_h','home_ab', 'home_h', 'hwin','awin'].sum()
Teamsaway = Teamsaway.reset_index()
Teamsaway = Teamsaway.rename(columns = {"visitor": "Team"}) 
Teamsaway

    Team  year  visitor_ab  visitor_h  home_ab  home_h  hwin  awin
0    ANA  1999        2828        735     2645     710    48    33
1    ANA  2000        2886        786     2742     734    45    36
2    ANA  2001        2815        716     2656     680    45    36
3    ANA  2002        2921        834     2654     660    36    45
4    ANA  2003        2802        756     2664     701    48    32
5    ARI  1999        2928        812     2751     694    33    48
6    ARI  2000        2798        703     2699     708    43    38
7    ARI  2001        2886        737     2661     632    37    44
8    ARI  2002        2799        702     2652     651    38    43
9    ARI  2003        2845        715     2700     669    42    39
10   ATL  1999        2901        777     2772     724    34    47
11   ATL  2000        2823        744     2710     696    37    44
12   ATL  2001        2816        730     2676     659    33    48
13   ATL  2002        2849        732     2667     643    31    49
14   ATL  2003        2945        829     2758     732    35    46
15   BAL  1999        2905        810     2638     708    44    37
16   BAL  2000        2896        786     2794     812    51    30
17   BAL  2001        2870        729     2775     771    48    33
18   BAL  2002        2789        682     2748     755    48    33
19   BAL  2003        2899        755     2812     820    51    31
20   BOS  1999        2857        758     2704     674    36    45
21   BOS  2000        2889        749     2694     660    38    43
22   BOS  2001        2833        734     2694     687    39    41
23   BOS  2002        2927        819     2653     627    30    51
24   BOS  2003        2924        768     2816     747    39    42
25   CHA  1999        2918        823     2766     782    44    37
26   CHA  2000        2909        813     2751     753    32    49
27   CHA  2001        2759        732     2667     715    44    37
28   CHA  2002        2824        725     2703     719    47    34
29   CHA  2003        2846        749     2633     680    46    35
..   ...   ...         ...        ...      ...     ...   ...   ...
120  SEA  1999        2851        757     2739     785    45    36
121  SEA  2000        2872        831     2693     746    37    44
122  SEA  2001        2965        868     2737     681    22    59
123  SEA  2002        2880        820     2734     713    36    45
124  SEA  2003        2887        802     2689     691    38    43
125  SFN  1999        2880        804     2769     781    44    37
126  SFN  2000        2867        784     2732     770    39    42
127  SFN  2001        2907        801     2729     727    40    41
128  SFN  2002        2868        784     2640     675    35    45
129  SFN  2003        2752        689     2590     657    37    43
130  SLN  1999        2839        750     2696     747    44    37
131  SLN  2000        2824        764     2667     711    36    45
132  SLN  2001        2775        710     2658     721    41    39
133  SLN  2002        2821        760     2640     693    36    45
134  SLN  2003        2914        781     2831     815    44    37
135  TBA  1999        2886        809     2718     767    45    36
136  TBA  2000        2836        739     2701     752    48    33
137  TBA  2001        2797        699     2676     738    56    25
138  TBA  2002        2779        669     2714     795    55    25
139  TBA  2003        2859        749     2663     719    54    27
140  TEX  1999        2895        816     2750     780    37    44
141  TEX  2000        2868        780     2788     835    52    29
142  TEX  2001        2865        768     2711     801    48    32
143  TEX  2002        2862        728     2716     713    51    30
144  TEX  2003        2877        708     2719     770    53    28
145  TOR  1999        2911        815     2753     765    37    44
146  TOR  2000        2911        794     2759     796    43    38
147  TOR  2001        2854        732     2738     753    40    40
148  TOR  2002        2852        723     2745     755    45    36
149  TOR  2003        2898        801     2730     733    36    45

[150 rows x 8 columns]

In [7]:
Teams2 = pd.merge(Teamshome, Teamsaway, on =['Team','year'])
Teams2['wins'] = Teams2['hwin_x']+Teams2['awin_y']
Teams2

,Team,year,visitor_ab_x,visitor_h_x,home_ab_x,home_h_x,hwin_x,awin_x,visitor_ab_y,visitor_h_y,home_ab_y,home_h_y,hwin_y,awin_y,wins
0,ANA,1999,2832,762,2666,669,37,44,2828,735,2645,710,48,33,70
1,ANA,2000,2867,800,2742,788,46,35,2886,786,2742,734,45,36,82
2,ANA,2001,2873,772,2736,731,39,42,2815,716,2656,680,45,36,75
3,ANA,2002,2799,685,2757,769,54,27,2921,834,2654,660,36,45,99
4,ANA,2003,2868,743,2685,717,45,37,2802,756,2664,701,48,32,77
5,ARI,1999,2814,693,2730,754,52,29,2928,812,2751,694,33,48,100
6,ARI,2000,2800,733,2729,763,47,34,2798,703,2699,708,43,38,85
7,ARI,2001,2804,720,2709,757,48,33,2886,737,2661,632,37,44,92
8,ARI,2002,2859,710,2709,769,55,26,2799,702,2652,651,38,43,98
9,ARI,2003,2817,710,2725,752,45,36,2845,715,2700,669,42,39,84
10,ATL,1999,2798,674,2668,704,56,25,2901,777,2772,724,34,47,103
11,ATL,2000,2833,732,2666,746,51,30,2823,744,2710,696,37,44,95
12,ATL,2001,2774,704,2682,702,40,41,2816,730,2676,659,33,48,88
13,ATL,2002,2762,659,2646,696,52,28,2849,732,2667,643,31,49,101
14,ATL,2003,2790,693,2725,779,55,26,2945,829,2758,732,35,46,101
15,BAL,1999,2827,760,2732,762,41,40,2905,810,2638,708,44,37,78
16,BAL,2000,2831,735,2653,722,44,37,2896,786,2794,812,51,30,74
17,BAL,2001,2823,733,2602,630,30,50,2870,729,2775,771,48,33,63
18,BAL,2002,2848,736,2702,671,34,47,2789,682,2748,755,48,33,67
19,BAL,2003,2871,759,2766,761,40,40,2899,755,2812,820,51,31,71
20,BOS,1999,2820,722,2722,793,49,32,2857,758,2704,674,36,45,94
21,BOS,2000,2879,773,2741,754,42,39,2889,749,2694,660,38,43,85
22,BOS,2001,2857,725,2772,759,41,40,2833,734,2694,687,39,41,82
23,BOS,2002,2800,712,2713,741,42,39,2927,819,2653,627,30,51,93
24,BOS,2003,2895,756,2845,899,53,28,2924,768,2816,747,39,42,95
25,CHA,1999,2934,826,2726,740,38,42,2918,823,2766,782,44,37,75
26,CHA,2000,2830,756,2737,802,46,35,2909,813,2751,753,32,49,95
27,CHA,2001,2841,750,2705,731,46,35,2759,732,2667,715,44,37,83
28,CHA,2002,2756,703,2678,750,47,34,2824,725,2703,719,47,34,81
29,CHA,2003,2757,684,2641,696,51,30,2846,749,2633,680,46,35,86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,SEA,1999,2888,828,2721,742,43,38,2851,757,2739,785,45,36,79
121,SEA,2000,2810,696,2625,650,47,34,2872,831,2693,746,37,44,91
122,SEA,2001,2753,612,2715,769,57,24,2965,868,2737,681,22,59,116
123,SEA,2002,2806,709,2689,711,48,33,2880,820,2734,713,36,45,93
124,SEA,2003,2738,649,2674,707,50,31,2887,802,2689,691,38,43,93
125,SFN,1999,2845,705,2683,703,49,32,2880,804,2769,781,44,37,86
126,SFN,2000,2726,682,2652,751,55,26,2867,784,2732,770,39,42,97
127,SFN,2001,2832,710,2705,692,49,32,2907,801,2729,727,40,41,90
128,SFN,2002,2742,674,2629,681,50,31,2868,784,2640,675,35,45,95
129,SFN,2003,2797,692,2704,751,57,24,2752,689,2590,657,37,43,100
130,SLN,1999,2866,772,2731,711,38,42,2839,750,2696,747,44,37,75
131,SLN,2000,2744,692,2654,717,50,31,2824,764,2667,711,36,45,95
132,SLN,2001,2758,668,2675,759,54,28,2775,710,2658,721,41,39,93
133,SLN,2002,2762,662,2684,715,52,29,2821,760,2640,693,36,45,97
134,SLN,2003,2857,729,2758,799,48,33,2914,781,2831,815,44,37,85
135,TBA,1999,2892,839,2700,722,33,48,2886,809,2718,767,45,36,69
136,TBA,2000,2894,801,2669,675,36,44,2836,739,2701,752,48,33,69
137,TBA,2001,2868,775,2727,727,37,44,2797,699,2676,738,56,25,62
138,TBA,2002,2904,772,2825,749,30,51,2779,669,2714,795,55,25,55
139,TBA,2003,2839,735,2795,752,36,45,2859,749,2663,719,54,27,63
140,TEX,1999,2928,846,2756,837,51,30,2895,816,2750,780,37,44,95
141,TEX,2000,2943,848,2780,821,42,39,2868,780,2788,835,52,29,71
142,TEX,2001,2995,869,2820,798,41,41,2865,768,2711,801,48,32,73
143,TEX,2002,2906,815,2756,782,42,39,2862,728,2716,713,51,30,72
144,TEX,2003,2929,855,2787,798,43,38,2877,708,2719,770,53,28,71
145,TOR,1999,2891,817,2731,765,40,41,2911,815,2753,765,37,44,84
146,TOR,2000,2910,819,2766,768,45,36,2911,794,2759,796,43,38,83
147,TOR,2001,2911,800,2809,757,40,42,2854,732,2738,753,40,40,80
148,TOR,2002,2838,749,2729,734,42,39,2852,723,2745,755,45,36,78
149,TOR,2003,2930,827,2763,779,41,40,2898,801,2730,733,36,45,86

In [16]:
season_win = Teams2.groupby('year')['home_ab_y'].mean()

In [17]:
season_win

year
1999    2719.166667
2000    2721.000000
2001    2706.666667
2002    2696.200000
2003    2712.966667
Name: home_ab_y, dtype: float64

# II. Calculating Performance Metrics

In [18]:
#Your Code Here
Teams2['BAFOR'] = (Teams2['home_h_x']+Teams2['visitor_h_y'])/(Teams2['home_ab_x']+Teams2['visitor_ab_y'])
Teams2['BAAGN'] = (Teams2['home_h_y']+Teams2['visitor_h_x'])/(Teams2['home_ab_y']+Teams2['visitor_ab_x'])

In [19]:
Teams3 = Teams2[['year', 'Team', 'wins','BAFOR','BAAGN']]
Teams3

     year Team  wins     BAFOR     BAAGN
0    1999  ANA    70  0.255552  0.268760
1    2000  ANA    82  0.279673  0.273489
2    2001  ANA    75  0.260674  0.262615
3    2002  ANA    99  0.282318  0.246653
4    2003  ANA    77  0.268453  0.261027
5    1999  ARI   100  0.276776  0.249236
6    2000  ARI    85  0.265243  0.262048
7    2001  ARI    92  0.267024  0.247392
8    2002  ARI    98  0.267066  0.246961
9    2003  ARI    84  0.263375  0.249955
10   1999  ATL   103  0.265936  0.250987
11   2000  ATL    95  0.271452  0.257622
12   2001  ATL    88  0.260458  0.250092
13   2002  ATL   101  0.259873  0.239823
14   2003  ATL   101  0.283598  0.256849
15   1999  BAL    78  0.278872  0.268618
16   2000  BAL    74  0.271761  0.275022
17   2001  BAL    63  0.248355  0.268667
18   2002  BAL    67  0.246403  0.266440
19   2003  BAL    71  0.267608  0.277846
20   1999  BOS    94  0.278007  0.252715
21   2000  BOS    85  0.266963  0.257133
22   2001  BOS    82  0.266369  0.254369
23   2002  BOS    93  0.276596  0.245553
24   2003  BOS    95  0.288958  0.263176
25   1999  CHA    75  0.276931  0.282105
26   2000  CHA    95  0.286043  0.270382
27   2001  CHA    83  0.267753  0.265977
28   2002  CHA    81  0.268084  0.260487
29   2003  CHA    86  0.263350  0.253061
..    ...  ...   ...       ...       ...
120  1999  SEA    79  0.269024  0.286654
121  2000  SEA    91  0.269420  0.262039
122  2001  SEA   116  0.288204  0.235519
123  2002  SEA    93  0.274915  0.256679
124  2003  SEA    93  0.271354  0.246914
125  1999  SFN    86  0.270897  0.264695
126  2000  SFN    97  0.278130  0.266032
127  2001  SFN    90  0.266037  0.258407
128  2002  SFN    95  0.266509  0.250650
129  2003  SFN   100  0.263930  0.250418
130  1999  SLN    75  0.262298  0.273103
131  2000  SLN    95  0.270354  0.259287
132  2001  SLN    93  0.269541  0.256462
133  2002  SLN    97  0.267938  0.250833
134  2003  SLN    85  0.278561  0.271449
135  1999  TBA    69  0.274078  0.286275
136  2000  TBA    69  0.256857  0.277569
137  2001  TBA    62  0.258146  0.272908
138  2002  TBA    55  0.253034  0.278925
139  2003  TBA    63  0.265476  0.264268
140  1999  TEX    95  0.292515  0.286368
141  2000  TEX    71  0.283463  0.293666
142  2001  TEX    73  0.275462  0.292674
143  2002  TEX    72  0.268779  0.271789
144  2003  TEX    71  0.265890  0.287712
145  1999  TOR    84  0.280043  0.280298
146  2000  TOR    83  0.275145  0.284883
147  2001  TOR    80  0.262935  0.274916
148  2002  TOR    78  0.261064  0.269389
149  2003  TOR    86  0.279103  0.275618

[150 rows x 5 columns]

In [20]:
TeamsGh = Teams.groupby(['year','home'])['hwin'].count()
TeamsGh = TeamsGh.reset_index()
TeamsGh = TeamsGh.rename(columns = {"home": 'Team'}) 

TeamsGa = Teams.groupby(['year','visitor'])['awin'].count()
TeamsGa = TeamsGa.reset_index()
TeamsGa = TeamsGa.rename(columns = {"visitor": 'Team'}) 

TeamsG = pd.merge(TeamsGh, TeamsGa, on =['Team','year'])
TeamsG['Games'] = TeamsG['hwin']+TeamsG['awin']
TeamsG = TeamsG[['year','Team','Games']]
TeamsG

     year Team  Games
0    1999  ANA    162
1    1999  ARI    162
2    1999  ATL    162
3    1999  BAL    162
4    1999  BOS    162
5    1999  CHA    162
6    1999  CHN    162
7    1999  CIN    163
8    1999  CLE    162
9    1999  COL    162
10   1999  DET    161
11   1999  FLO    162
12   1999  HOU    162
13   1999  KCA    161
14   1999  LAN    162
15   1999  MIL    161
16   1999  MIN    161
17   1999  MON    162
18   1999  NYA    162
19   1999  NYN    163
20   1999  OAK    162
21   1999  PHI    162
22   1999  PIT    161
23   1999  SDN    162
24   1999  SEA    162
25   1999  SFN    162
26   1999  SLN    161
27   1999  TBA    162
28   1999  TEX    162
29   1999  TOR    162
..    ...  ...    ...
120  2003  ANA    162
121  2003  ARI    162
122  2003  ATL    162
123  2003  BAL    163
124  2003  BOS    162
125  2003  CHA    162
126  2003  CHN    162
127  2003  CIN    162
128  2003  CLE    162
129  2003  COL    162
130  2003  DET    162
131  2003  FLO    162
132  2003  HOU    162
133  2003  KCA    162
134  2003  LAN    162
135  2003  MIL    162
136  2003  MIN    162
137  2003  MON    162
138  2003  NYA    163
139  2003  NYN    161
140  2003  OAK    162
141  2003  PHI    162
142  2003  PIT    162
143  2003  SDN    162
144  2003  SEA    162
145  2003  SFN    161
146  2003  SLN    162
147  2003  TBA    162
148  2003  TEX    162
149  2003  TOR    162

[150 rows x 3 columns]

In [21]:
Teams3 = pd.merge(Teams3, TeamsG, on =['Team','year'])
Teams3

     year Team  wins     BAFOR     BAAGN  Games
0    1999  ANA    70  0.255552  0.268760    162
1    2000  ANA    82  0.279673  0.273489    162
2    2001  ANA    75  0.260674  0.262615    162
3    2002  ANA    99  0.282318  0.246653    162
4    2003  ANA    77  0.268453  0.261027    162
5    1999  ARI   100  0.276776  0.249236    162
6    2000  ARI    85  0.265243  0.262048    162
7    2001  ARI    92  0.267024  0.247392    162
8    2002  ARI    98  0.267066  0.246961    162
9    2003  ARI    84  0.263375  0.249955    162
10   1999  ATL   103  0.265936  0.250987    162
11   2000  ATL    95  0.271452  0.257622    162
12   2001  ATL    88  0.260458  0.250092    162
13   2002  ATL   101  0.259873  0.239823    161
14   2003  ATL   101  0.283598  0.256849    162
15   1999  BAL    78  0.278872  0.268618    162
16   2000  BAL    74  0.271761  0.275022    162
17   2001  BAL    63  0.248355  0.268667    162
18   2002  BAL    67  0.246403  0.266440    162
19   2003  BAL    71  0.267608  0.277846    163
20   1999  BOS    94  0.278007  0.252715    162
21   2000  BOS    85  0.266963  0.257133    162
22   2001  BOS    82  0.266369  0.254369    161
23   2002  BOS    93  0.276596  0.245553    162
24   2003  BOS    95  0.288958  0.263176    162
25   1999  CHA    75  0.276931  0.282105    162
26   2000  CHA    95  0.286043  0.270382    162
27   2001  CHA    83  0.267753  0.265977    162
28   2002  CHA    81  0.268084  0.260487    162
29   2003  CHA    86  0.263350  0.253061    162
..    ...  ...   ...       ...       ...    ...
120  1999  SEA    79  0.269024  0.286654    162
121  2000  SEA    91  0.269420  0.262039    162
122  2001  SEA   116  0.288204  0.235519    162
123  2002  SEA    93  0.274915  0.256679    162
124  2003  SEA    93  0.271354  0.246914    162
125  1999  SFN    86  0.270897  0.264695    162
126  2000  SFN    97  0.278130  0.266032    162
127  2001  SFN    90  0.266037  0.258407    162
128  2002  SFN    95  0.266509  0.250650    162
129  2003  SFN   100  0.263930  0.250418    161
130  1999  SLN    75  0.262298  0.273103    161
131  2000  SLN    95  0.270354  0.259287    162
132  2001  SLN    93  0.269541  0.256462    162
133  2002  SLN    97  0.267938  0.250833    162
134  2003  SLN    85  0.278561  0.271449    162
135  1999  TBA    69  0.274078  0.286275    162
136  2000  TBA    69  0.256857  0.277569    161
137  2001  TBA    62  0.258146  0.272908    162
138  2002  TBA    55  0.253034  0.278925    161
139  2003  TBA    63  0.265476  0.264268    162
140  1999  TEX    95  0.292515  0.286368    162
141  2000  TEX    71  0.283463  0.293666    162
142  2001  TEX    73  0.275462  0.292674    162
143  2002  TEX    72  0.268779  0.271789    162
144  2003  TEX    71  0.265890  0.287712    162
145  1999  TOR    84  0.280043  0.280298    162
146  2000  TOR    83  0.275145  0.284883    162
147  2001  TOR    80  0.262935  0.274916    162
148  2002  TOR    78  0.261064  0.269389    162
149  2003  TOR    86  0.279103  0.275618    162

[150 rows x 6 columns]

In [22]:
Teams3['wpc'] = Teams3['wins']/Teams3['Games']
Teams3

     year Team  wins     BAFOR     BAAGN  Games       wpc
0    1999  ANA    70  0.255552  0.268760    162  0.432099
1    2000  ANA    82  0.279673  0.273489    162  0.506173
2    2001  ANA    75  0.260674  0.262615    162  0.462963
3    2002  ANA    99  0.282318  0.246653    162  0.611111
4    2003  ANA    77  0.268453  0.261027    162  0.475309
5    1999  ARI   100  0.276776  0.249236    162  0.617284
6    2000  ARI    85  0.265243  0.262048    162  0.524691
7    2001  ARI    92  0.267024  0.247392    162  0.567901
8    2002  ARI    98  0.267066  0.246961    162  0.604938
9    2003  ARI    84  0.263375  0.249955    162  0.518519
10   1999  ATL   103  0.265936  0.250987    162  0.635802
11   2000  ATL    95  0.271452  0.257622    162  0.586420
12   2001  ATL    88  0.260458  0.250092    162  0.543210
13   2002  ATL   101  0.259873  0.239823    161  0.627329
14   2003  ATL   101  0.283598  0.256849    162  0.623457
15   1999  BAL    78  0.278872  0.268618    162  0.481481
16   2000  BAL    74  0.271761  0.275022    162  0.456790
17   2001  BAL    63  0.248355  0.268667    162  0.388889
18   2002  BAL    67  0.246403  0.266440    162  0.413580
19   2003  BAL    71  0.267608  0.277846    163  0.435583
20   1999  BOS    94  0.278007  0.252715    162  0.580247
21   2000  BOS    85  0.266963  0.257133    162  0.524691
22   2001  BOS    82  0.266369  0.254369    161  0.509317
23   2002  BOS    93  0.276596  0.245553    162  0.574074
24   2003  BOS    95  0.288958  0.263176    162  0.586420
25   1999  CHA    75  0.276931  0.282105    162  0.462963
26   2000  CHA    95  0.286043  0.270382    162  0.586420
27   2001  CHA    83  0.267753  0.265977    162  0.512346
28   2002  CHA    81  0.268084  0.260487    162  0.500000
29   2003  CHA    86  0.263350  0.253061    162  0.530864
..    ...  ...   ...       ...       ...    ...       ...
120  1999  SEA    79  0.269024  0.286654    162  0.487654
121  2000  SEA    91  0.269420  0.262039    162  0.561728
122  2001  SEA   116  0.288204  0.235519    162  0.716049
123  2002  SEA    93  0.274915  0.256679    162  0.574074
124  2003  SEA    93  0.271354  0.246914    162  0.574074
125  1999  SFN    86  0.270897  0.264695    162  0.530864
126  2000  SFN    97  0.278130  0.266032    162  0.598765
127  2001  SFN    90  0.266037  0.258407    162  0.555556
128  2002  SFN    95  0.266509  0.250650    162  0.586420
129  2003  SFN   100  0.263930  0.250418    161  0.621118
130  1999  SLN    75  0.262298  0.273103    161  0.465839
131  2000  SLN    95  0.270354  0.259287    162  0.586420
132  2001  SLN    93  0.269541  0.256462    162  0.574074
133  2002  SLN    97  0.267938  0.250833    162  0.598765
134  2003  SLN    85  0.278561  0.271449    162  0.524691
135  1999  TBA    69  0.274078  0.286275    162  0.425926
136  2000  TBA    69  0.256857  0.277569    161  0.428571
137  2001  TBA    62  0.258146  0.272908    162  0.382716
138  2002  TBA    55  0.253034  0.278925    161  0.341615
139  2003  TBA    63  0.265476  0.264268    162  0.388889
140  1999  TEX    95  0.292515  0.286368    162  0.586420
141  2000  TEX    71  0.283463  0.293666    162  0.438272
142  2001  TEX    73  0.275462  0.292674    162  0.450617
143  2002  TEX    72  0.268779  0.271789    162  0.444444
144  2003  TEX    71  0.265890  0.287712    162  0.438272
145  1999  TOR    84  0.280043  0.280298    162  0.518519
146  2000  TOR    83  0.275145  0.284883    162  0.512346
147  2001  TOR    80  0.262935  0.274916    162  0.493827
148  2002  TOR    78  0.261064  0.269389    162  0.481481
149  2003  TOR    86  0.279103  0.275618    162  0.530864

[150 rows x 7 columns]

In [33]:
Teams3['BA_DIFF'] = Teams3['BAFOR'] - Teams3['BAAGN']
Teams3.sort_values(by='BA_DIFF')

     year Team  wins     BAFOR     BAAGN  Games       wpc   BA_DIFF
54   2003  DET    43  0.240029  0.285714    162  0.265432 -0.045685
53   2002  DET    55  0.247873  0.284820    161  0.341615 -0.036948
39   2003  CIN    69  0.244872  0.278209    162  0.425926 -0.033337
30   1999  CHN    67  0.257388  0.286144    162  0.413580 -0.028756
52   2001  DET    66  0.259888  0.288506    162  0.407407 -0.028618
99   2003  NYN    66  0.246583  0.273425    161  0.409938 -0.026842
138  2002  TBA    55  0.253034  0.278925    161  0.341615 -0.025891
68   2002  KCA    62  0.255646  0.281084    162  0.382716 -0.025438
112  2001  PIT    62  0.246943  0.272197    162  0.382716 -0.025254
43   2002  CLE    74  0.248755  0.273883    162  0.456790 -0.025128
113  2002  PIT    72  0.243902  0.267517    161  0.447205 -0.023615
76   2000  MIL    73  0.245551  0.268756    163  0.447853 -0.023205
49   2003  COL    74  0.266763  0.289806    162  0.456790 -0.023043
79   2003  MIL    68  0.256489  0.278605    162  0.419753 -0.022116
144  2003  TEX    71  0.265890  0.287712    162  0.438272 -0.021823
118  2002  SDN    66  0.252584  0.273593    162  0.407407 -0.021010
136  2000  TBA    69  0.256857  0.277569    161  0.428571 -0.020712
17   2001  BAL    63  0.248355  0.268667    162  0.388889 -0.020312
18   2002  BAL    67  0.246403  0.266440    162  0.413580 -0.020037
80   1999  MIN    63  0.263876  0.283046    161  0.391304 -0.019169
87   2001  MON    68  0.253021  0.272039    162  0.419753 -0.019018
55   1999  FLO    64  0.262639  0.281487    162  0.395062 -0.018848
117  2001  SDN    79  0.251551  0.269278    162  0.487654 -0.017728
120  1999  SEA    79  0.269024  0.286654    162  0.487654 -0.017630
142  2001  TEX    73  0.275462  0.292674    162  0.450617 -0.017213
81   2000  MIN    69  0.269991  0.286868    162  0.425926 -0.016877
37   2001  CIN    66  0.262225  0.278674    162  0.407407 -0.016449
86   2000  MON    67  0.266486  0.282461    162  0.413580 -0.015975
38   2002  CIN    78  0.253382  0.268983    162  0.481481 -0.015601
78   2002  MIL    56  0.252816  0.268275    162  0.345679 -0.015459
..    ...  ...   ...       ...       ...    ...       ...       ...
129  2003  SFN   100  0.263930  0.250418    161  0.621118  0.013512
11   2000  ATL    95  0.271452  0.257622    162  0.586420  0.013830
91   2000  NYA    87  0.277358  0.263462    161  0.540373  0.013896
64   2003  HOU    87  0.262583  0.248390    162  0.537037  0.014193
102  2001  OAK   102  0.263592  0.249324    162  0.629630  0.014268
10   1999  ATL   103  0.265936  0.250987    162  0.635802  0.014949
26   2000  CHA    95  0.286043  0.270382    162  0.586420  0.015662
128  2002  SFN    95  0.266509  0.250650    162  0.586420  0.015859
133  2002  SLN    97  0.267938  0.250833    162  0.598765  0.017105
47   2001  COL    73  0.292267  0.274680    162  0.450617  0.017587
123  2002  SEA    93  0.274915  0.256679    162  0.574074  0.018236
41   2000  CLE    90  0.288404  0.270014    162  0.555556  0.018390
34   2003  CHN    88  0.259286  0.240546    162  0.543210  0.018740
93   2002  NYA   103  0.274951  0.255996    161  0.639752  0.018955
7    2001  ARI    92  0.267024  0.247392    162  0.567901  0.019632
13   2002  ATL   101  0.259873  0.239823    161  0.627329  0.020049
8    2002  ARI    98  0.267066  0.246961    162  0.604938  0.020105
40   1999  CLE    97  0.289137  0.268106    162  0.598765  0.021032
73   2002  LAN    92  0.263594  0.241525    162  0.567901  0.022068
124  2003  SEA    93  0.271354  0.246914    162  0.574074  0.024440
20   1999  BOS    94  0.278007  0.252715    162  0.580247  0.025291
24   2003  BOS    95  0.288958  0.263176    162  0.586420  0.025782
14   2003  ATL   101  0.283598  0.256849    162  0.623457  0.026749
90   1999  NYA    98  0.281609  0.254631    162  0.604938  0.026978
95   1999  NYN    97  0.278715  0.251558    163  0.595092  0.027157
5    1999  ARI   100  0.276776  0.249236    162  0.617284  0.027540
35   1999  CIN    96  0.271907  0.241335    163  0.588957  0.030572
23   2002  BOS    93  0.276596  0.245553    162  0.574074  0.031043
3    2002  ANA    99  0.282318  0.246653    162  0.611111  0.035664
122  2001  SEA   116  0.288204  0.235519    162  0.716049  0.052685

[150 rows x 8 columns]

In [36]:
Teams3[Teams3['Games'] != 162].shape

(28, 8)

In [25]:
Teamswpc = Teams2[['year','Team','hwin_x','awin_y']]
Teamswpc

     year Team  hwin_x  awin_y
0    1999  ANA      37      33
1    2000  ANA      46      36
2    2001  ANA      39      36
3    2002  ANA      54      45
4    2003  ANA      45      32
5    1999  ARI      52      48
6    2000  ARI      47      38
7    2001  ARI      48      44
8    2002  ARI      55      43
9    2003  ARI      45      39
10   1999  ATL      56      47
11   2000  ATL      51      44
12   2001  ATL      40      48
13   2002  ATL      52      49
14   2003  ATL      55      46
15   1999  BAL      41      37
16   2000  BAL      44      30
17   2001  BAL      30      33
18   2002  BAL      34      33
19   2003  BAL      40      31
20   1999  BOS      49      45
21   2000  BOS      42      43
22   2001  BOS      41      41
23   2002  BOS      42      51
24   2003  BOS      53      42
25   1999  CHA      38      37
26   2000  CHA      46      49
27   2001  CHA      46      37
28   2002  CHA      47      34
29   2003  CHA      51      35
..    ...  ...     ...     ...
120  1999  SEA      43      36
121  2000  SEA      47      44
122  2001  SEA      57      59
123  2002  SEA      48      45
124  2003  SEA      50      43
125  1999  SFN      49      37
126  2000  SFN      55      42
127  2001  SFN      49      41
128  2002  SFN      50      45
129  2003  SFN      57      43
130  1999  SLN      38      37
131  2000  SLN      50      45
132  2001  SLN      54      39
133  2002  SLN      52      45
134  2003  SLN      48      37
135  1999  TBA      33      36
136  2000  TBA      36      33
137  2001  TBA      37      25
138  2002  TBA      30      25
139  2003  TBA      36      27
140  1999  TEX      51      44
141  2000  TEX      42      29
142  2001  TEX      41      32
143  2002  TEX      42      30
144  2003  TEX      43      28
145  1999  TOR      40      44
146  2000  TOR      45      38
147  2001  TOR      40      40
148  2002  TOR      42      36
149  2003  TOR      41      45

[150 rows x 4 columns]

In [27]:
TeamsGh = TeamsGh.rename(columns = {"hwin": 'hgame'})
TeamsGa = TeamsGa.rename(columns = {"awin": 'agame'})
Teamswpc = pd.merge(Teamswpc, TeamsGh, on =['Team','year'])
Teamswpc = pd.merge(Teamswpc, TeamsGa, on =['Team','year'])
Teamswpc

     year Team  hwin_x  awin_y  hgame  agame
0    1999  ANA      37      33     81     81
1    2000  ANA      46      36     81     81
2    2001  ANA      39      36     81     81
3    2002  ANA      54      45     81     81
4    2003  ANA      45      32     82     80
5    1999  ARI      52      48     81     81
6    2000  ARI      47      38     81     81
7    2001  ARI      48      44     81     81
8    2002  ARI      55      43     81     81
9    2003  ARI      45      39     81     81
10   1999  ATL      56      47     81     81
11   2000  ATL      51      44     81     81
12   2001  ATL      40      48     81     81
13   2002  ATL      52      49     81     80
14   2003  ATL      55      46     81     81
15   1999  BAL      41      37     81     81
16   2000  BAL      44      30     81     81
17   2001  BAL      30      33     80     82
18   2002  BAL      34      33     81     81
19   2003  BAL      40      31     81     82
20   1999  BOS      49      45     81     81
21   2000  BOS      42      43     81     81
22   2001  BOS      41      41     81     80
23   2002  BOS      42      51     81     81
24   2003  BOS      53      42     81     81
25   1999  CHA      38      37     81     81
26   2000  CHA      46      49     81     81
27   2001  CHA      46      37     81     81
28   2002  CHA      47      34     81     81
29   2003  CHA      51      35     81     81
..    ...  ...     ...     ...    ...    ...
120  1999  SEA      43      36     81     81
121  2000  SEA      47      44     81     81
122  2001  SEA      57      59     81     81
123  2002  SEA      48      45     81     81
124  2003  SEA      50      43     81     81
125  1999  SFN      49      37     81     81
126  2000  SFN      55      42     81     81
127  2001  SFN      49      41     81     81
128  2002  SFN      50      45     81     81
129  2003  SFN      57      43     81     80
130  1999  SLN      38      37     80     81
131  2000  SLN      50      45     81     81
132  2001  SLN      54      39     82     80
133  2002  SLN      52      45     81     81
134  2003  SLN      48      37     81     81
135  1999  TBA      33      36     81     81
136  2000  TBA      36      33     80     81
137  2001  TBA      37      25     81     81
138  2002  TBA      30      25     81     80
139  2003  TBA      36      27     81     81
140  1999  TEX      51      44     81     81
141  2000  TEX      42      29     81     81
142  2001  TEX      41      32     82     80
143  2002  TEX      42      30     81     81
144  2003  TEX      43      28     81     81
145  1999  TOR      40      44     81     81
146  2000  TOR      45      38     81     81
147  2001  TOR      40      40     82     80
148  2002  TOR      42      36     81     81
149  2003  TOR      41      45     81     81

[150 rows x 6 columns]

In [28]:
Teamswpc['wpc_h'] = Teamswpc['hwin_x']/Teamswpc['hgame']
Teamswpc['wpc_a'] = Teamswpc['awin_y']/Teamswpc['agame']

In [30]:
Teamswpc['wpc_diff'] = Teamswpc['wpc_h'] - Teamswpc['wpc_a']
Teamswpc

     year Team  hwin_x  awin_y  hgame  agame     wpc_h     wpc_a  wpc_diff
0    1999  ANA      37      33     81     81  0.456790  0.407407  0.049383
1    2000  ANA      46      36     81     81  0.567901  0.444444  0.123457
2    2001  ANA      39      36     81     81  0.481481  0.444444  0.037037
3    2002  ANA      54      45     81     81  0.666667  0.555556  0.111111
4    2003  ANA      45      32     82     80  0.548780  0.400000  0.148780
5    1999  ARI      52      48     81     81  0.641975  0.592593  0.049383
6    2000  ARI      47      38     81     81  0.580247  0.469136  0.111111
7    2001  ARI      48      44     81     81  0.592593  0.543210  0.049383
8    2002  ARI      55      43     81     81  0.679012  0.530864  0.148148
9    2003  ARI      45      39     81     81  0.555556  0.481481  0.074074
10   1999  ATL      56      47     81     81  0.691358  0.580247  0.111111
11   2000  ATL      51      44     81     81  0.629630  0.543210  0.086420
12   2001  ATL      40      48     81     81  0.493827  0.592593 -0.098765
13   2002  ATL      52      49     81     80  0.641975  0.612500  0.029475
14   2003  ATL      55      46     81     81  0.679012  0.567901  0.111111
15   1999  BAL      41      37     81     81  0.506173  0.456790  0.049383
16   2000  BAL      44      30     81     81  0.543210  0.370370  0.172840
17   2001  BAL      30      33     80     82  0.375000  0.402439 -0.027439
18   2002  BAL      34      33     81     81  0.419753  0.407407  0.012346
19   2003  BAL      40      31     81     82  0.493827  0.378049  0.115778
20   1999  BOS      49      45     81     81  0.604938  0.555556  0.049383
21   2000  BOS      42      43     81     81  0.518519  0.530864 -0.012346
22   2001  BOS      41      41     81     80  0.506173  0.512500 -0.006327
23   2002  BOS      42      51     81     81  0.518519  0.629630 -0.111111
24   2003  BOS      53      42     81     81  0.654321  0.518519  0.135802
25   1999  CHA      38      37     81     81  0.469136  0.456790  0.012346
26   2000  CHA      46      49     81     81  0.567901  0.604938 -0.037037
27   2001  CHA      46      37     81     81  0.567901  0.456790  0.111111
28   2002  CHA      47      34     81     81  0.580247  0.419753  0.160494
29   2003  CHA      51      35     81     81  0.629630  0.432099  0.197531
..    ...  ...     ...     ...    ...    ...       ...       ...       ...
120  1999  SEA      43      36     81     81  0.530864  0.444444  0.086420
121  2000  SEA      47      44     81     81  0.580247  0.543210  0.037037
122  2001  SEA      57      59     81     81  0.703704  0.728395 -0.024691
123  2002  SEA      48      45     81     81  0.592593  0.555556  0.037037
124  2003  SEA      50      43     81     81  0.617284  0.530864  0.086420
125  1999  SFN      49      37     81     81  0.604938  0.456790  0.148148
126  2000  SFN      55      42     81     81  0.679012  0.518519  0.160494
127  2001  SFN      49      41     81     81  0.604938  0.506173  0.098765
128  2002  SFN      50      45     81     81  0.617284  0.555556  0.061728
129  2003  SFN      57      43     81     80  0.703704  0.537500  0.166204
130  1999  SLN      38      37     80     81  0.475000  0.456790  0.018210
131  2000  SLN      50      45     81     81  0.617284  0.555556  0.061728
132  2001  SLN      54      39     82     80  0.658537  0.487500  0.171037
133  2002  SLN      52      45     81     81  0.641975  0.555556  0.086420
134  2003  SLN      48      37     81     81  0.592593  0.456790  0.135802
135  1999  TBA      33      36     81     81  0.407407  0.444444 -0.037037
136  2000  TBA      36      33     80     81  0.450000  0.407407  0.042593
137  2001  TBA      37      25     81     81  0.456790  0.308642  0.148148
138  2002  TBA      30      25     81     80  0.370370  0.312500  0.057870
139  2003  TBA      36      27     81     81  0.444444  0.333333  0.111111
140  1999  TEX      51      44     81     81  0.629630  0.543210  0.086420
141  2000  TEX      42      29     81     81  0.518519  0.358025  0.160494
142  2001  TEX      41      32     82     80  0.500000  0.400000  0.100000
143  2002  TEX      42      30     81     81  0.518519  0.370370  0.148148
144  2003  TEX      43      28     81     81  0.530864  0.345679  0.185185
145  1999  TOR      40      44     81     81  0.493827  0.543210 -0.049383
146  2000  TOR      45      38     81     81  0.555556  0.469136  0.086420
147  2001  TOR      40      40     82     80  0.487805  0.500000 -0.012195
148  2002  TOR      42      36     81     81  0.518519  0.444444  0.074074
149  2003  TOR      41      45     81     81  0.506173  0.555556 -0.049383

[150 rows x 9 columns]

In [32]:
Teamswpc.sort_values(by='wpc_diff',ascending=False)

     year Team  hwin_x  awin_y  hgame  agame     wpc_h     wpc_a  wpc_diff
49   2003  COL      49      25     81     81  0.604938  0.308642  0.296296
48   2002  COL      47      26     81     81  0.580247  0.320988  0.259259
89   2003  MON      52      31     81     81  0.641975  0.382716  0.259259
104  2003  OAK      57      39     81     81  0.703704  0.481481  0.222222
115  1999  SDN      46      28     81     81  0.567901  0.345679  0.222222
100  1999  OAK      52      35     81     81  0.641975  0.432099  0.209877
57   2001  FLO      46      30     80     82  0.575000  0.365854  0.209146
29   2003  CHA      51      35     81     81  0.629630  0.432099  0.197531
96   2000  NYN      55      39     81     81  0.679012  0.481481  0.197531
118  2002  SDN      41      25     81     81  0.506173  0.308642  0.197531
144  2003  TEX      43      28     81     81  0.530864  0.345679  0.185185
88   2002  MON      49      34     81     81  0.604938  0.419753  0.185185
59   2003  FLO      53      38     81     81  0.654321  0.469136  0.185185
112  2001  PIT      38      24     81     81  0.469136  0.296296  0.172840
46   2000  COL      48      34     81     81  0.592593  0.419753  0.172840
16   2000  BAL      44      30     81     81  0.543210  0.370370  0.172840
132  2001  SLN      54      39     82     80  0.658537  0.487500  0.171037
83   2002  MIN      54      40     81     80  0.666667  0.500000  0.166667
129  2003  SFN      57      43     81     80  0.703704  0.537500  0.166204
28   2002  CHA      47      34     81     81  0.580247  0.419753  0.160494
126  2000  SFN      55      42     81     81  0.679012  0.518519  0.160494
141  2000  TEX      42      29     81     81  0.518519  0.358025  0.160494
58   2002  FLO      46      33     81     81  0.567901  0.407407  0.160494
4    2003  ANA      45      32     82     80  0.548780  0.400000  0.148780
125  1999  SFN      49      37     81     81  0.604938  0.456790  0.148148
109  2003  PHI      49      37     81     81  0.604938  0.456790  0.148148
137  2001  TBA      37      25     81     81  0.456790  0.308642  0.148148
143  2002  TEX      42      30     81     81  0.518519  0.370370  0.148148
8    2002  ARI      55      43     81     81  0.679012  0.530864  0.148148
68   2002  KCA      37      25     81     81  0.456790  0.308642  0.148148
..    ...  ...     ...     ...    ...    ...       ...       ...       ...
108  2002  PHI      40      40     80     81  0.500000  0.493827  0.006173
36   2000  CIN      43      42     82     81  0.524390  0.518519  0.005872
87   2001  MON      34      34     81     81  0.419753  0.419753  0.000000
34   2003  CHN      44      44     81     81  0.543210  0.543210  0.000000
73   2002  LAN      46      46     81     81  0.567901  0.567901  0.000000
22   2001  BOS      41      41     81     80  0.506173  0.512500 -0.006327
147  2001  TOR      40      40     82     80  0.487805  0.500000 -0.012195
21   2000  BOS      42      43     81     81  0.518519  0.530864 -0.012346
80   1999  MIN      31      32     81     80  0.382716  0.400000 -0.017284
94   2003  NYA      50      51     82     81  0.609756  0.629630 -0.019874
42   2001  CLE      44      47     80     82  0.550000  0.573171 -0.023171
69   2003  KCA      40      43     80     82  0.500000  0.524390 -0.024390
122  2001  SEA      57      59     81     81  0.703704  0.728395 -0.024691
38   2002  CIN      38      40     81     81  0.469136  0.493827 -0.024691
90   1999  NYA      48      50     81     81  0.592593  0.617284 -0.024691
17   2001  BAL      30      33     80     82  0.375000  0.402439 -0.027439
40   1999  CLE      47      50     81     81  0.580247  0.617284 -0.037037
135  1999  TBA      33      36     81     81  0.407407  0.444444 -0.037037
70   1999  LAN      37      40     81     81  0.456790  0.493827 -0.037037
26   2000  CHA      46      49     81     81  0.567901  0.604938 -0.037037
145  1999  TOR      40      44     81     81  0.493827  0.543210 -0.049383
149  2003  TOR      41      45     81     81  0.506173  0.555556 -0.049383
62   2001  HOU      44      49     81     81  0.543210  0.604938 -0.061728
79   2003  MIL      31      37     81     81  0.382716  0.456790 -0.074074
35   1999  CIN      45      51     82     81  0.548780  0.629630 -0.080849
12   2001  ATL      40      48     81     81  0.493827  0.592593 -0.098765
117  2001  SDN      35      44     81     81  0.432099  0.543210 -0.111111
23   2002  BOS      42      51     81     81  0.518519  0.629630 -0.111111
75   1999  MIL      32      42     80     81  0.400000  0.518519 -0.118519
37   2001  CIN      27      39     81     81  0.333333  0.481481 -0.148148

[150 rows x 9 columns]

# III. Running Regressions

In [38]:
#Your Code Here
import statsmodels.formula.api as smf
WinBA_lm = smf.ols(formula = 'wpc ~ BAFOR + BAAGN', data=Teams3).fit()
WinBA_lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    wpc   R-squared:                       0.720
Model:                            OLS   Adj. R-squared:                  0.716
Method:                 Least Squares   F-statistic:                     188.6
Date:                Mon, 16 Mar 2026   Prob (F-statistic):           2.60e-41
Time:                        11:08:01   Log-Likelihood:                 265.67
No. Observations:                 150   AIC:                            -525.3
Df Residuals:                     147   BIC:                            -516.3
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.6016      0.099      6.069      0.000       0.406       0.797
BAFOR          3.7863      0.300     12.619      0.000       3.193       4.379
BAAGN         -4.1691      0.258    -16.141      0.000      -4.680      -3.659
==============================================================================
Omnibus:                        0.210   Durbin-Watson:                   1.530
Prob(Omnibus):                  0.900   Jarque-Bera (JB):                0.033
Skew:                           0.005   Prob(JB):                        0.983
Kurtosis:                       3.073   Cond. No.                         97.7
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [39]:
WinBAR_lm = smf.ols(formula = 'wpc ~ I(BAFOR - BAAGN)', data=Teams3).fit()
WinBAR_lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    wpc   R-squared:                       0.718
Model:                            OLS   Adj. R-squared:                  0.716
Method:                 Least Squares   F-statistic:                     376.0
Date:                Mon, 16 Mar 2026   Prob (F-statistic):           1.81e-42
Time:                        11:09:31   Log-Likelihood:                 265.13
No. Observations:                 150   AIC:                            -526.3
Df Residuals:                     148   BIC:                            -520.2
Df Model:                           1
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept            0.4997      0.003    147.125      0.000       0.493       0.506
I(BAFOR - BAAGN)     4.0099      0.207     19.390      0.000       3.601       4.419
==============================================================================
Omnibus:                        0.360   Durbin-Watson:                   1.507
Prob(Omnibus):                  0.835   Jarque-Bera (JB):                0.108
Skew:                          -0.003   Prob(JB):                        0.948
Kurtosis:                       3.131   Cond. No.                         60.9
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [40]:
from statsmodels.iolib.summary2 import summary_col
Header = ['1','2']
Table_1 = summary_col([WinBA_lm,WinBAR_lm],\
                      regressor_order=['Intercept','BAFOR','BAAGN'],model_names = Header)
print(Table_1)

==================================
                    1        2
----------------------------------
Intercept        0.6016   0.4997
                 (0.0991) (0.0034)
BAFOR            3.7863
                 (0.3000)
BAAGN            -4.1691
                 (0.2583)
I(BAFOR - BAAGN)          4.0099
                          (0.2068)
==================================
Standard errors in parentheses.