In [1]:
# First we load the packages
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# I. Building the Dataset: Player Stats

In [2]:
# Read in salary data retrieved from Lahman's Database
Salary = pd.read_csv("../Data/Salaries.csv")

# Read in batting
Batting = pd.read_csv("../Data/Batting.csv")

In [5]:
#Your Code Here
Salary = Salary[Salary['salary']>0]
Salary

       yearID teamID lgID   playerID    salary
0        1985    ATL   NL  barkele01    870000
1        1985    ATL   NL  bedrost01    550000
2        1985    ATL   NL  benedbr01    545000
3        1985    ATL   NL   campri01    633333
4        1985    ATL   NL  ceronri01    625000
5        1985    ATL   NL  chambch01    800000
6        1985    ATL   NL  dedmoje01    150000
7        1985    ATL   NL  forstte01    483333
8        1985    ATL   NL  garbege01    772000
9        1985    ATL   NL  harpete01    250000
10       1985    ATL   NL  hornebo01   1500000
11       1985    ATL   NL  hubbagl01    455000
12       1985    ATL   NL  mahleri01    407500
13       1985    ATL   NL  mcmurcr01    275000
14       1985    ATL   NL  mumphje01    775000
15       1985    ATL   NL  murphda05   1625000
16       1985    ATL   NL  oberkke01    616667
17       1985    ATL   NL  perezpa01    450000
18       1985    ATL   NL  perryge01    120000
19       1985    ATL   NL  ramirra01    750000
20       1985    ATL   NL  suttebr01   1354167
21       1985    ATL   NL  washicl01    800000
22       1985    BAL   AL  boddimi01    625000
23       1985    BAL   AL  dauerri01    480000
24       1985    BAL   AL  davisst02    437500
25       1985    BAL   AL  dempsri01    512500
26       1985    BAL   AL  dwyerji01    375000
27       1985    BAL   AL  flanami01    641667
28       1985    BAL   AL   fordda01    450000
29       1985    BAL   AL  grosswa01    483333
...       ...    ...  ...        ...       ...
26398    2016    TOR   AL  stromma01    515900
26399    2016    TOR   AL  tholejo01    800000
26400    2016    TOR   AL  travide01    511200
26401    2016    TOR   AL  tulowtr01  20000000
26402    2016    WAS   NL  barreaa01    519400
26403    2016    WAS   NL  belisma01   1250000
26404    2016    WAS   NL   drewst01   3000000
26405    2016    WAS   NL  espinda01   2875000
26406    2016    WAS   NL  gonzagi01  12100000
26407    2016    WAS   NL  harpebr03   5000000
26408    2016    WAS   NL  heisech01   1250000
26409    2016    WAS   NL  kellesh01   4000000
26410    2016    WAS   NL  lobatjo01   1387500
26411    2016    WAS   NL  murphda08   8000000
26412    2016    WAS   NL  papeljo01  10936574
26413    2016    WAS   NL  perezol01   3000000
26414    2016    WAS   NL  petityu01   2500000
26415    2016    WAS   NL  ramoswi01   5350000
26416    2016    WAS   NL  rendoan01   2800000
26417    2016    WAS   NL  reverbe01   6250000
26418    2016    WAS   NL  riverfe01    516100
26419    2016    WAS   NL  roarkta01    543400
26420    2016    WAS   NL  robincl01    534900
26421    2016    WAS   NL   rossjo01    514400
26422    2016    WAS   NL  scherma01  22142857
26423    2016    WAS   NL  strasst01  10400000
26424    2016    WAS   NL  taylomi02    524000
26425    2016    WAS   NL  treinbl01    524900
26426    2016    WAS   NL  werthja01  21733615
26427    2016    WAS   NL  zimmery01  14000000

[26426 rows x 5 columns]

In [6]:
Salary['lnSal'] = np.log(Salary['salary'])
Salary = Salary.rename(columns={'yearID':'SalYear'})
Salary

       SalYear teamID lgID   playerID    salary      lnSal
0         1985    ATL   NL  barkele01    870000  13.676248
1         1985    ATL   NL  bedrost01    550000  13.217674
2         1985    ATL   NL  benedbr01    545000  13.208541
3         1985    ATL   NL   campri01    633333  13.358752
4         1985    ATL   NL  ceronri01    625000  13.345507
5         1985    ATL   NL  chambch01    800000  13.592367
6         1985    ATL   NL  dedmoje01    150000  11.918391
7         1985    ATL   NL  forstte01    483333  13.088461
8         1985    ATL   NL  garbege01    772000  13.556740
9         1985    ATL   NL  harpete01    250000  12.429216
10        1985    ATL   NL  hornebo01   1500000  14.220976
11        1985    ATL   NL  hubbagl01    455000  13.028053
12        1985    ATL   NL  mahleri01    407500  12.917796
13        1985    ATL   NL  mcmurcr01    275000  12.524526
14        1985    ATL   NL  mumphje01    775000  13.560618
15        1985    ATL   NL  murphda05   1625000  14.301018
16        1985    ATL   NL  oberkke01    616667  13.332084
17        1985    ATL   NL  perezpa01    450000  13.017003
18        1985    ATL   NL  perryge01    120000  11.695247
19        1985    ATL   NL  ramirra01    750000  13.527828
20        1985    ATL   NL  suttebr01   1354167  14.118697
21        1985    ATL   NL  washicl01    800000  13.592367
22        1985    BAL   AL  boddimi01    625000  13.345507
23        1985    BAL   AL  dauerri01    480000  13.081541
24        1985    BAL   AL  davisst02    437500  12.988832
25        1985    BAL   AL  dempsri01    512500  13.147056
26        1985    BAL   AL  dwyerji01    375000  12.834681
27        1985    BAL   AL  flanami01    641667  13.371825
28        1985    BAL   AL   fordda01    450000  13.017003
29        1985    BAL   AL  grosswa01    483333  13.088461
...        ...    ...  ...        ...       ...        ...
26398     2016    TOR   AL  stromma01    515900  13.153668
26399     2016    TOR   AL  tholejo01    800000  13.592367
26400     2016    TOR   AL  travide01    511200  13.144516
26401     2016    TOR   AL  tulowtr01  20000000  16.811243
26402     2016    WAS   NL  barreaa01    519400  13.160430
26403     2016    WAS   NL  belisma01   1250000  14.038654
26404     2016    WAS   NL   drewst01   3000000  14.914123
26405     2016    WAS   NL  espinda01   2875000  14.871563
26406     2016    WAS   NL  gonzagi01  12100000  16.308716
26407     2016    WAS   NL  harpebr03   5000000  15.424948
26408     2016    WAS   NL  heisech01   1250000  14.038654
26409     2016    WAS   NL  kellesh01   4000000  15.201805
26410     2016    WAS   NL  lobatjo01   1387500  14.143014
26411     2016    WAS   NL  murphda08   8000000  15.894952
26412     2016    WAS   NL  papeljo01  10936574  16.207623
26413     2016    WAS   NL  perezol01   3000000  14.914123
26414     2016    WAS   NL  petityu01   2500000  14.731801
26415     2016    WAS   NL  ramoswi01   5350000  15.492607
26416     2016    WAS   NL  rendoan01   2800000  14.845130
26417     2016    WAS   NL  reverbe01   6250000  15.648092
26418     2016    WAS   NL  riverfe01    516100  13.154056
26419     2016    WAS   NL  roarkta01    543400  13.205601
26420     2016    WAS   NL  robincl01    534900  13.189835
26421     2016    WAS   NL   rossjo01    514400  13.150756
26422     2016    WAS   NL  scherma01  22142857  16.913026
26423     2016    WAS   NL  strasst01  10400000  16.157316
26424     2016    WAS   NL  taylomi02    524000  13.169247
26425     2016    WAS   NL  treinbl01    524900  13.170963
26426     2016    WAS   NL  werthja01  21733615  16.894371
26427     2016    WAS   NL  zimmery01  14000000  16.454568

[26426 rows x 6 columns]

In [7]:
Master = Salary
Batting = Batting.groupby(['playerID','yearID']).sum()
Batting.reset_index(inplace=True)
Batting = Batting[(Batting.yearID >= 1998) & (Batting.yearID <= 2016) & (Batting.AB >= 130)].copy()
Batting['PA'] = Batting['AB'] + Batting['BB'] + Batting['HBP'] + Batting['SH'] + Batting['SF']

Batting['OBP'] = (Batting['H'] + Batting['BB'] + Batting['HBP'])/(Batting['AB'] + Batting['BB']
                                                                  + Batting['HBP'] + Batting['SF'])

Batting['SLG'] = ((Batting['H'] - Batting['Doubles'] - Batting['Triples'] - Batting['HR']) 
                  + 2*Batting['Doubles'] + 3*Batting['Triples'] + 4*Batting['HR'])/Batting['AB']

In [10]:
Batting['BA'] = Batting['H'] / Batting['AB']
display(Batting)

,playerID,yearID,stint,G,AB,R,H,Doubles,Triples,HR,...,SO,IBB,HBP,SH,SF,GIDP,PA,OBP,SLG,BA
98,abbotje01,1998,1,89,244,33,68,14,1,12,...,28.0,1.0,0.0,2.0,5.0,2.0,260.0,0.298450,0.491803,0.278689
100,abbotje01,2000,1,80,215,31,59,15,1,3,...,38.0,1.0,2.0,2.0,1.0,2.0,241.0,0.343096,0.395349,0.274419
113,abbotku01,1994,1,101,345,41,86,17,3,9,...,98.0,1.0,5.0,3.0,2.0,5.0,371.0,0.290761,0.394203,0.249275
114,abbotku01,1995,1,120,420,60,107,18,7,17,...,110.0,4.0,5.0,2.0,5.0,6.0,468.0,0.317597,0.452381,0.254762
115,abbotku01,1996,1,109,320,37,81,18,7,8,...,99.0,1.0,3.0,4.0,0.0,7.0,349.0,0.307246,0.428125,0.253125
116,abbotku01,1997,1,94,252,35,69,18,2,6,...,68.0,3.0,1.0,6.0,0.0,5.0,273.0,0.314607,0.432540,0.273810
117,abbotku01,1998,3,77,194,26,51,13,1,5,...,53.0,0.0,2.0,1.0,3.0,5.0,212.0,0.308057,0.417526,0.262887
118,abbotku01,1999,1,96,286,41,78,17,2,8,...,69.0,0.0,0.0,2.0,1.0,4.0,305.0,0.310231,0.430070,0.272727
119,abbotku01,2000,1,79,157,22,34,7,1,6,...,51.0,2.0,1.0,0.0,1.0,2.0,173.0,0.283237,0.388535,0.216561
144,abercre01,2006,1,111,255,39,54,12,2,5,...,78.0,2.0,3.0,4.0,1.0,2.0,281.0,0.270758,0.333333,0.211765
148,abernbr01,2001,1,79,304,43,82,17,1,5,...,35.0,1.0,0.0,3.0,1.0,3.0,335.0,0.328313,0.381579,0.269737
149,abernbr01,2002,1,117,463,46,112,18,4,2,...,46.0,0.0,6.0,8.0,2.0,8.0,504.0,0.288306,0.311015,0.241901
194,abreubo01,1997,1,59,188,22,47,10,2,3,...,48.0,0.0,1.0,0.0,0.0,0.0,210.0,0.328571,0.372340,0.250000
195,abreubo01,1998,1,151,497,68,155,29,6,17,...,133.0,14.0,0.0,4.0,4.0,6.0,589.0,0.408547,0.496982,0.311871
196,abreubo01,1999,1,152,546,118,183,35,11,20,...,113.0,8.0,3.0,0.0,4.0,13.0,662.0,0.445619,0.549451,0.335165
197,abreubo01,2000,1,154,576,103,182,42,10,25,...,116.0,9.0,1.0,0.0,3.0,12.0,680.0,0.416176,0.553819,0.315972
198,abreubo01,2001,1,162,588,118,170,48,4,31,...,137.0,11.0,1.0,0.0,9.0,13.0,704.0,0.393466,0.542517,0.289116
199,abreubo01,2002,1,157,572,102,176,50,6,20,...,117.0,9.0,3.0,0.0,6.0,11.0,685.0,0.413139,0.520979,0.307692
200,abreubo01,2003,1,158,577,99,173,35,1,20,...,126.0,13.0,2.0,0.0,7.0,13.0,695.0,0.408633,0.467938,0.299827
201,abreubo01,2004,1,159,574,118,173,47,1,30,...,116.0,10.0,5.0,0.0,7.0,5.0,713.0,0.427770,0.543554,0.301394
202,abreubo01,2005,1,162,588,104,168,37,1,24,...,134.0,15.0,6.0,0.0,8.0,7.0,719.0,0.404729,0.474490,0.285714
203,abreubo01,2006,3,156,548,98,163,41,2,15,...,138.0,6.0,3.0,2.0,9.0,13.0,686.0,0.423977,0.461679,0.297445
204,abreubo01,2007,1,158,605,123,171,40,5,16,...,115.0,0.0,3.0,0.0,7.0,11.0,699.0,0.369099,0.444628,0.282645
205,abreubo01,2008,1,156,609,100,180,39,4,20,...,109.0,2.0,1.0,0.0,1.0,14.0,684.0,0.371345,0.471264,0.295567
206,abreubo01,2009,1,152,563,96,165,29,3,15,...,113.0,7.0,1.0,0.0,9.0,15.0,667.0,0.389805,0.435169,0.293073
207,abreubo01,2010,1,154,573,88,146,41,1,20,...,132.0,3.0,2.0,0.0,5.0,13.0,667.0,0.352324,0.434555,0.254799
208,abreubo01,2011,1,142,502,54,127,30,1,8,...,113.0,5.0,1.0,1.0,3.0,8.0,585.0,0.352740,0.364542,0.252988
209,abreubo01,2012,3,100,219,29,53,11,1,3,...,56.0,3.0,0.0,0.0,1.0,7.0,257.0,0.350195,0.342466,0.242009
210,abreubo01,2014,1,78,133,12,33,9,0,1,...,21.0,0.0,0.0,0.0,2.0,3.0,155.0,0.341935,0.338346,0.248120
212,abreujo02,2014,1,145,556,80,176,35,2,36,...,131.0,15.0,11.0,0.0,4.0,14.0,622.0,0.382637,0.580935,0.316547
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94987,zeileto01,2001,1,151,531,66,141,25,1,10,...,102.0,3.0,6.0,0.0,2.0,15.0,612.0,0.359477,0.372881,0.265537
94988,zeileto01,2002,1,144,506,61,138,23,0,18,...,92.0,3.0,1.0,0.0,7.0,27.0,580.0,0.353448,0.424901,0.272727
94989,zeileto01,2003,3,100,299,40,68,10,2,11,...,54.0,0.0,3.0,0.0,5.0,6.0,341.0,0.307918,0.384615,0.227425
94990,zeileto01,2004,1,137,348,30,81,16,0,9,...,83.0,1.0,1.0,1.0,2.0,13.0,396.0,0.318987,0.356322,0.232759
95105,zimmery01,2006,1,157,614,84,176,47,3,20,...,120.0,7.0,2.0,1.0,4.0,15.0,682.0,0.350954,0.470684,0.286645
95106,zimmery01,2007,1,162,653,99,174,43,5,24,...,125.0,3.0,3.0,0.0,5.0,26.0,722.0,0.329640,0.457887,0.266462
95107,zimmery01,2008,1,106,428,51,121,24,1,14,...,71.0,1.0,3.0,0.0,4.0,12.0,466.0,0.332618,0.441589,0.282710
95108,zimmery01,2009,1,157,610,110,178,37,3,33,...,119.0,9.0,2.0,0.0,9.0,22.0,693.0,0.363636,0.524590,0.291803
95109,zimmery01,2010,1,142,525,85,161,32,0,25,...,98.0,6.0,4.0,0.0,5.0,16.0,603.0,0.388060,0.510476,0.306667
95110,zimmery01,2011,1,101,395,52,114,21,2,12,...,73.0,4.0,1.0,0.0,3.0,14.0,440.0,0.354545,0.443038,0.288608
95111,zimmery01,2012,1,145,578,93,163,36,1,25,...,116.0,8.0,2.0,0.0,4.0,20.0,641.0,0.346334,0.477509,0.282007
95112,zimmery01,2013,1,147,568,84,156,26,2,26,...,133.0,2.0,2.0,0.0,3.0,16.0,633.0,0.344392,0.464789,0.274648
95113,zimmery01,2014,1,61,214,26,60,19,1,5,...,37.0,0.0,0.0,0.0,4.0,6.0,240.0,0.341667,0.448598,0.280374
95114,zimmery01,2015,1,95,346,43,86,25,1,16,...,79.0,0.0,1.0,0.0,10.0,13.0,390.0,0.307692,0.465318,0.248555
95115,zimmery01,2016,1,115,427,60,93,18,1,15,...,104.0,1.0,5.0,0.0,6.0,12.0,467.0,0.271949,0.370023,0.217799
95170,zobribe01,2006,1,52,183,10,41,6,2,2,...,26.0,1.0,0.0,2.0,3.0,2.0,198.0,0.260204,0.311475,0.224044
95172,zobribe01,2008,1,62,198,32,50,10,2,12,...,37.0,1.0,2.0,0.0,2.0,4.0,227.0,0.339207,0.505051,0.252525
95173,zobribe01,2009,1,152,501,91,149,28,7,27,...,104.0,4.0,2.0,1.0,4.0,7.0,599.0,0.404682,0.542914,0.297405
95174,zobribe01,2010,1,151,541,77,129,28,2,10,...,107.0,1.0,3.0,7.0,12.0,10.0,655.0,0.345679,0.353050,0.238447
95175,zobribe01,2011,1,156,588,99,158,46,6,20,...,128.0,1.0,2.0,2.0,5.0,9.0,674.0,0.352679,0.469388,0.268707
95176,zobribe01,2012,1,157,560,88,151,39,7,20,...,103.0,7.0,3.0,2.0,6.0,13.0,668.0,0.376877,0.471429,0.269643
95177,zobribe01,2013,1,157,612,77,168,36,3,12,...,91.0,4.0,7.0,1.0,6.0,18.0,698.0,0.354376,0.401961,0.274510
95178,zobribe01,2014,1,146,570,83,155,34,3,10,...,84.0,4.0,1.0,2.0,6.0,8.0,654.0,0.354294,0.394737,0.271930
95179,zobribe01,2015,3,126,467,76,129,36,3,13,...,56.0,3.0,1.0,0.0,5.0,8.0,535.0,0.358879,0.449679,0.276231
95180,zobribe01,2016,1,147,523,94,142,31,3,18,...,82.0,6.0,4.0,4.0,4.0,17.0,631.0,0.385965,0.445507,0.271511
95216,zuninmi01,2013,1,52,173,22,37,5,0,5,...,49.0,0.0,3.0,0.0,1.0,5.0,193.0,0.290155,0.329480,0.213873
95217,zuninmi01,2014,1,131,438,51,87,20,2,22,...,158.0,1.0,17.0,0.0,4.0,12.0,476.0,0.254202,0.404110,0.198630
95218,zuninmi01,2015,1,112,350,28,61,11,0,11,...,132.0,0.0,5.0,8.0,2.0,6.0,386.0,0.230159,0.300000,0.174286
95219,zuninmi01,2016,1,55,164,16,34,7,0,12,...,65.0,0.0,6.0,0.0,1.0,0.0,192.0,0.317708,0.469512,0.207317
95222,zupcibo01,1993,1,141,286,40,69,24,2,2,...,54.0,2.0,2.0,8.0,3.0,7.0,326.0,0.308176,0.360140,0.241259

In [11]:
Batting = Batting[(Batting.yearID >= 1998) & (Batting.yearID <= 2006) & (Batting.AB >= 130)].copy()
Batting

,playerID,yearID,stint,G,AB,R,H,Doubles,Triples,HR,...,SO,IBB,HBP,SH,SF,GIDP,PA,OBP,SLG,BA
98,abbotje01,1998,1,89,244,33,68,14,1,12,...,28.0,1.0,0.0,2.0,5.0,2.0,260.0,0.298450,0.491803,0.278689
100,abbotje01,2000,1,80,215,31,59,15,1,3,...,38.0,1.0,2.0,2.0,1.0,2.0,241.0,0.343096,0.395349,0.274419
117,abbotku01,1998,3,77,194,26,51,13,1,5,...,53.0,0.0,2.0,1.0,3.0,5.0,212.0,0.308057,0.417526,0.262887
118,abbotku01,1999,1,96,286,41,78,17,2,8,...,69.0,0.0,0.0,2.0,1.0,4.0,305.0,0.310231,0.430070,0.272727
119,abbotku01,2000,1,79,157,22,34,7,1,6,...,51.0,2.0,1.0,0.0,1.0,2.0,173.0,0.283237,0.388535,0.216561
144,abercre01,2006,1,111,255,39,54,12,2,5,...,78.0,2.0,3.0,4.0,1.0,2.0,281.0,0.270758,0.333333,0.211765
148,abernbr01,2001,1,79,304,43,82,17,1,5,...,35.0,1.0,0.0,3.0,1.0,3.0,335.0,0.328313,0.381579,0.269737
149,abernbr01,2002,1,117,463,46,112,18,4,2,...,46.0,0.0,6.0,8.0,2.0,8.0,504.0,0.288306,0.311015,0.241901
195,abreubo01,1998,1,151,497,68,155,29,6,17,...,133.0,14.0,0.0,4.0,4.0,6.0,589.0,0.408547,0.496982,0.311871
196,abreubo01,1999,1,152,546,118,183,35,11,20,...,113.0,8.0,3.0,0.0,4.0,13.0,662.0,0.445619,0.549451,0.335165
197,abreubo01,2000,1,154,576,103,182,42,10,25,...,116.0,9.0,1.0,0.0,3.0,12.0,680.0,0.416176,0.553819,0.315972
198,abreubo01,2001,1,162,588,118,170,48,4,31,...,137.0,11.0,1.0,0.0,9.0,13.0,704.0,0.393466,0.542517,0.289116
199,abreubo01,2002,1,157,572,102,176,50,6,20,...,117.0,9.0,3.0,0.0,6.0,11.0,685.0,0.413139,0.520979,0.307692
200,abreubo01,2003,1,158,577,99,173,35,1,20,...,126.0,13.0,2.0,0.0,7.0,13.0,695.0,0.408633,0.467938,0.299827
201,abreubo01,2004,1,159,574,118,173,47,1,30,...,116.0,10.0,5.0,0.0,7.0,5.0,713.0,0.427770,0.543554,0.301394
202,abreubo01,2005,1,162,588,104,168,37,1,24,...,134.0,15.0,6.0,0.0,8.0,7.0,719.0,0.404729,0.474490,0.285714
203,abreubo01,2006,3,156,548,98,163,41,2,15,...,138.0,6.0,3.0,2.0,9.0,13.0,686.0,0.423977,0.461679,0.297445
437,adamsru01,2005,1,139,481,68,123,27,5,8,...,57.0,1.0,3.0,3.0,8.0,5.0,545.0,0.324723,0.382536,0.255717
438,adamsru01,2006,1,90,251,31,55,14,1,3,...,41.0,0.0,1.0,3.0,3.0,5.0,280.0,0.281588,0.318725,0.219124
567,agbaybe01,1999,1,101,276,42,79,18,3,14,...,60.0,4.0,3.0,0.0,3.0,8.0,314.0,0.363057,0.525362,0.286232
568,agbaybe01,2000,1,119,350,59,101,19,1,15,...,68.0,2.0,7.0,0.0,3.0,6.0,414.0,0.391304,0.477143,0.288571
569,agbaybe01,2001,1,91,296,28,82,14,2,6,...,73.0,0.0,5.0,1.0,1.0,11.0,339.0,0.363905,0.398649,0.277027
570,agbaybe01,2002,3,61,154,15,35,6,0,4,...,40.0,1.0,0.0,0.0,1.0,5.0,171.0,0.298246,0.344156,0.227273
868,alexama02,1998,1,108,264,34,60,10,1,5,...,66.0,1.0,1.0,5.0,1.0,6.0,289.0,0.278169,0.329545,0.227273
869,alexama02,1999,1,90,177,17,48,11,2,0,...,38.0,0.0,0.0,1.0,1.0,1.0,189.0,0.308511,0.355932,0.271186
870,alexama02,2000,1,101,194,30,41,4,3,4,...,41.0,0.0,0.0,2.0,0.0,0.0,209.0,0.260870,0.324742,0.211340
918,alfoned01,1998,1,144,557,94,155,28,2,17,...,77.0,1.0,3.0,2.0,3.0,11.0,630.0,0.355096,0.427289,0.278276
919,alfoned01,1999,1,158,628,123,191,41,1,27,...,85.0,2.0,3.0,1.0,9.0,14.0,726.0,0.384828,0.501592,0.304140
920,alfoned01,2000,1,150,544,109,176,40,2,25,...,70.0,1.0,5.0,0.0,6.0,12.0,650.0,0.424615,0.542279,0.323529
921,alfoned01,2001,1,124,457,64,111,22,0,17,...,62.0,0.0,5.0,1.0,5.0,7.0,519.0,0.322394,0.402626,0.242888
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94628,younger01,2004,1,104,344,55,99,25,2,1,...,28.0,0.0,8.0,4.0,3.0,9.0,402.0,0.376884,0.380814,0.287791
94629,younger01,2005,1,56,142,22,39,9,0,2,...,12.0,0.0,0.0,3.0,0.0,4.0,163.0,0.356250,0.380282,0.274648
94630,younger01,2006,3,60,138,20,28,6,1,3,...,17.0,1.0,2.0,2.0,3.0,7.0,159.0,0.280255,0.326087,0.202899
94689,youngke01,1998,1,159,592,88,160,40,2,27,...,127.0,1.0,11.0,0.0,9.0,20.0,656.0,0.327744,0.481419,0.270270
94690,youngke01,1999,1,156,584,103,174,41,6,26,...,124.0,5.0,12.0,0.0,4.0,13.0,675.0,0.386667,0.522260,0.297945
94691,youngke01,2000,1,132,496,77,128,27,0,20,...,96.0,1.0,8.0,0.0,5.0,15.0,541.0,0.310536,0.433468,0.258065
94692,youngke01,2001,1,142,449,53,104,33,0,14,...,119.0,3.0,11.0,0.0,5.0,17.0,507.0,0.309665,0.398664,0.231626
94693,youngke01,2002,1,146,468,60,115,26,1,16,...,101.0,2.0,4.0,0.0,3.0,13.0,525.0,0.321905,0.408120,0.245726
94719,youngmi02,2001,1,106,386,57,96,18,4,11,...,91.0,0.0,3.0,9.0,5.0,9.0,429.0,0.297619,0.401554,0.248705
94720,youngmi02,2002,1,156,573,77,150,26,8,9,...,112.0,1.0,0.0,13.0,6.0,14.0,633.0,0.308065,0.382199,0.261780
94721,youngmi02,2003,1,160,666,106,204,33,9,14,...,103.0,1.0,1.0,3.0,7.0,14.0,713.0,0.339437,0.445946,0.306306
94722,youngmi02,2004,1,160,690,114,216,33,9,22,...,89.0,1.0,1.0,0.0,4.0,11.0,739.0,0.353180,0.482609,0.313043
94723,youngmi02,2005,1,159,668,114,221,40,5,24,...,91.0,0.0,3.0,0.0,3.0,20.0,732.0,0.385246,0.513473,0.330838
94724,youngmi02,2006,1,162,691,93,217,52,3,14,...,96.0,0.0,1.0,0.0,8.0,27.0,748.0,0.355615,0.458755,0.314038
94937,zaungr01,1998,1,106,298,19,56,12,2,5,...,52.0,2.0,1.0,2.0,2.0,7.0,338.0,0.273810,0.291946,0.187919
94939,zaungr01,2000,1,83,234,36,64,11,0,7,...,34.0,3.0,3.0,0.0,2.0,4.0,282.0,0.390071,0.410256,0.273504
94941,zaungr01,2002,1,76,185,18,41,7,1,3,...,36.0,1.0,2.0,2.0,1.0,4.0,202.0,0.275000,0.318919,0.221622
94942,zaungr01,2003,3,74,166,15,38,8,0,4,...,21.0,0.0,1.0,1.0,2.0,5.0,189.0,0.308511,0.349398,0.228916
94943,zaungr01,2004,1,107,338,46,91,24,0,6,...,61.0,3.0,6.0,0.0,1.0,7.0,392.0,0.367347,0.393491,0.269231
94944,zaungr01,2005,1,133,434,61,109,18,1,11,...,70.0,2.0,0.0,0.0,5.0,11.0,512.0,0.355469,0.373272,0.251152
94945,zaungr01,2006,1,99,290,39,79,19,0,12,...,42.0,3.0,3.0,0.0,5.0,10.0,339.0,0.362832,0.462069,0.272414
94984,zeileto01,1998,6,158,572,85,155,32,3,19,...,90.0,2.0,4.0,1.0,7.0,12.0,653.0,0.349693,0.437063,0.270979
94985,zeileto01,1999,1,156,588,80,172,41,1,24,...,94.0,3.0,4.0,1.0,7.0,20.0,656.0,0.354198,0.488095,0.292517
94986,zeileto01,2000,1,153,544,67,146,36,3,22,...,85.0,4.0,2.0,0.0,3.0,15.0,623.0,0.356340,0.466912,0.268382
94987,zeileto01,2001,1,151,531,66,141,25,1,10,...,102.0,3.0,6.0,0.0,2.0,15.0,612.0,0.359477,0.372881,0.265537
94988,zeileto01,2002,1,144,506,61,138,23,0,18,...,92.0,3.0,1.0,0.0,7.0,27.0,580.0,0.353448,0.424901,0.272727
94989,zeileto01,2003,3,100,299,40,68,10,2,11,...,54.0,0.0,3.0,0.0,5.0,6.0,341.0,0.307918,0.384615,0.227425
94990,zeileto01,2004,1,137,348,30,81,16,0,9,...,83.0,1.0,1.0,1.0,2.0,13.0,396.0,0.318987,0.356322,0.232759
95105,zimmery01,2006,1,157,614,84,176,47,3,20,...,120.0,7.0,2.0,1.0,4.0,15.0,682.0,0.350954,0.470684,0.286645
95170,zobribe01,2006,1,52,183,10,41,6,2,2,...,26.0,1.0,0.0,2.0,3.0,2.0,198.0,0.260204,0.311475,0.224044

In [12]:
Batting['SalYear'] = Batting['yearID'] + 1
Master = pd.merge(Batting, Master, on=['SalYear', 'playerID'])
display(Master)

,playerID,yearID,stint,G,AB,R,H,Doubles,Triples,HR,...,GIDP,PA,OBP,SLG,BA,SalYear,teamID,lgID,salary,lnSal
0,abbotje01,1998,1,89,244,33,68,14,1,12,...,2.0,260.0,0.298450,0.491803,0.278689,1999,CHA,AL,255000,12.449019
1,abbotje01,2000,1,80,215,31,59,15,1,3,...,2.0,241.0,0.343096,0.395349,0.274419,2001,FLO,NL,300000,12.611538
2,abbotku01,1998,3,77,194,26,51,13,1,5,...,5.0,212.0,0.308057,0.417526,0.262887,1999,COL,NL,900000,13.710150
3,abbotku01,1999,1,96,286,41,78,17,2,8,...,4.0,305.0,0.310231,0.430070,0.272727,2000,NYN,NL,500000,13.122363
4,abbotku01,2000,1,79,157,22,34,7,1,6,...,2.0,173.0,0.283237,0.388535,0.216561,2001,ATL,NL,600000,13.304685
5,abernbr01,2001,1,79,304,43,82,17,1,5,...,3.0,335.0,0.328313,0.381579,0.269737,2002,TBA,AL,215000,12.278393
6,abernbr01,2002,1,117,463,46,112,18,4,2,...,8.0,504.0,0.288306,0.311015,0.241901,2003,TBA,AL,300000,12.611538
7,abreubo01,1998,1,151,497,68,155,29,6,17,...,6.0,589.0,0.408547,0.496982,0.311871,1999,PHI,NL,400000,12.899220
8,abreubo01,1999,1,152,546,118,183,35,11,20,...,13.0,662.0,0.445619,0.549451,0.335165,2000,PHI,NL,2933333,14.891650
9,abreubo01,2000,1,154,576,103,182,42,10,25,...,12.0,680.0,0.416176,0.553819,0.315972,2001,PHI,NL,4983000,15.421543
10,abreubo01,2001,1,162,588,118,170,48,4,31,...,13.0,704.0,0.393466,0.542517,0.289116,2002,PHI,NL,6333333,15.661337
11,abreubo01,2002,1,157,572,102,176,50,6,20,...,11.0,685.0,0.413139,0.520979,0.307692,2003,PHI,NL,9100000,16.023785
12,abreubo01,2003,1,158,577,99,173,35,1,20,...,13.0,695.0,0.408633,0.467938,0.299827,2004,PHI,NL,10600000,16.176365
13,abreubo01,2004,1,159,574,118,173,47,1,30,...,5.0,713.0,0.427770,0.543554,0.301394,2005,PHI,NL,13100000,16.388123
14,abreubo01,2005,1,162,588,104,168,37,1,24,...,7.0,719.0,0.404729,0.474490,0.285714,2006,PHI,NL,13600000,16.425580
15,abreubo01,2006,3,156,548,98,163,41,2,15,...,13.0,686.0,0.423977,0.461679,0.297445,2007,NYA,AL,15000000,16.523561
16,adamsru01,2005,1,139,481,68,123,27,5,8,...,5.0,545.0,0.324723,0.382536,0.255717,2006,TOR,AL,343000,12.745486
17,agbaybe01,1999,1,101,276,42,79,18,3,14,...,8.0,314.0,0.363057,0.525362,0.286232,2000,NYN,NL,220000,12.301383
18,agbaybe01,2000,1,119,350,59,101,19,1,15,...,6.0,414.0,0.391304,0.477143,0.288571,2001,NYN,NL,260000,12.468437
19,agbaybe01,2001,1,91,296,28,82,14,2,6,...,11.0,339.0,0.363905,0.398649,0.277027,2002,COL,NL,600000,13.304685
20,alexama02,1998,1,108,264,34,60,10,1,5,...,6.0,289.0,0.278169,0.329545,0.227273,1999,CHN,NL,475000,13.071070
21,alexama02,1999,1,90,177,17,48,11,2,0,...,1.0,189.0,0.308511,0.355932,0.271186,2000,BOS,AL,612500,13.325304
22,alfoned01,1998,1,144,557,94,155,28,2,17,...,11.0,630.0,0.355096,0.427289,0.278276,1999,NYN,NL,2800000,14.845130
23,alfoned01,1999,1,158,628,123,191,41,1,27,...,14.0,726.0,0.384828,0.501592,0.304140,2000,NYN,NL,4225000,15.256530
24,alfoned01,2000,1,150,544,109,176,40,2,25,...,12.0,650.0,0.424615,0.542279,0.323529,2001,NYN,NL,5750000,15.564710
25,alfoned01,2001,1,124,457,64,111,22,0,17,...,7.0,519.0,0.322394,0.402626,0.242888,2002,NYN,NL,6200000,15.640060
26,alfoned01,2002,1,135,490,78,151,26,0,16,...,5.0,562.0,0.391459,0.459184,0.308163,2003,SFN,NL,4000000,15.201805
27,alfoned01,2003,1,142,514,56,133,25,2,13,...,14.0,586.0,0.334477,0.391051,0.258755,2004,SFN,NL,6500000,15.687313
28,alfoned01,2004,1,139,519,66,150,26,1,11,...,15.0,576.0,0.350174,0.406551,0.289017,2005,SFN,NL,7500000,15.830414
29,alfoned01,2005,1,109,368,36,102,17,1,2,...,11.0,402.0,0.326683,0.345109,0.277174,2006,LAA,AL,8000000,15.894952
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3084,younger01,2000,1,153,607,98,180,40,2,6,...,12.0,690.0,0.367496,0.398682,0.296540,2001,CHN,NL,4500000,15.319588
3085,younger01,2001,1,149,603,98,168,43,4,6,...,15.0,672.0,0.333333,0.393035,0.278607,2002,MIL,NL,2000000,14.508658
3086,younger01,2002,1,138,496,57,139,29,3,3,...,14.0,553.0,0.337615,0.368952,0.280242,2003,MIL,NL,2000000,14.508658
3087,younger01,2003,3,135,475,80,119,20,1,15,...,12.0,541.0,0.335807,0.391579,0.250526,2004,TEX,AL,1000000,13.815511
3088,younger01,2004,1,104,344,55,99,25,2,1,...,9.0,402.0,0.376884,0.380814,0.287791,2005,SDN,NL,850000,13.652992
3089,younger01,2005,1,56,142,22,39,9,0,2,...,4.0,163.0,0.356250,0.380282,0.274648,2006,SDN,NL,700000,13.458836
3090,youngke01,1998,1,159,592,88,160,40,2,27,...,20.0,656.0,0.327744,0.481419,0.270270,1999,PIT,NL,2100000,14.557448
3091,youngke01,1999,1,156,584,103,174,41,6,26,...,13.0,675.0,0.386667,0.522260,0.297945,2000,PIT,NL,5625000,15.542732
3092,youngke01,2000,1,132,496,77,128,27,0,20,...,15.0,541.0,0.310536,0.433468,0.258065,2001,PIT,NL,6125000,15.627889
3093,youngke01,2001,1,142,449,53,104,33,0,14,...,17.0,507.0,0.309665,0.398664,0.231626,2002,PIT,NL,5625000,15.542732
3094,youngke01,2002,1,146,468,60,115,26,1,16,...,13.0,525.0,0.321905,0.408120,0.245726,2003,PIT,NL,6625000,15.706361
3095,youngmi02,2001,1,106,386,57,96,18,4,11,...,9.0,429.0,0.297619,0.401554,0.248705,2002,TEX,AL,250000,12.429216
3096,youngmi02,2002,1,156,573,77,150,26,8,9,...,14.0,633.0,0.308065,0.382199,0.261780,2003,TEX,AL,415000,12.936034
3097,youngmi02,2003,1,160,666,106,204,33,9,14,...,14.0,713.0,0.339437,0.445946,0.306306,2004,TEX,AL,450000,13.017003
3098,youngmi02,2004,1,160,690,114,216,33,9,22,...,11.0,739.0,0.353180,0.482609,0.313043,2005,TEX,AL,2575000,14.761360
3099,youngmi02,2005,1,159,668,114,221,40,5,24,...,20.0,732.0,0.385246,0.513473,0.330838,2006,TEX,AL,3075000,14.938815
3100,youngmi02,2006,1,162,691,93,217,52,3,14,...,27.0,748.0,0.355615,0.458755,0.314038,2007,TEX,AL,3575000,15.089476
3101,zaungr01,1998,1,106,298,19,56,12,2,5,...,7.0,338.0,0.273810,0.291946,0.187919,1999,TEX,AL,450000,13.017003
3102,zaungr01,2000,1,83,234,36,64,11,0,7,...,4.0,282.0,0.390071,0.410256,0.273504,2001,KCA,AL,1150000,13.955273
3103,zaungr01,2002,1,76,185,18,41,7,1,3,...,4.0,202.0,0.275000,0.318919,0.221622,2003,HOU,NL,1200000,13.997832
3104,zaungr01,2004,1,107,338,46,91,24,0,6,...,7.0,392.0,0.367347,0.393491,0.269231,2005,TOR,AL,950000,13.764217
3105,zaungr01,2005,1,133,434,61,109,18,1,11,...,11.0,512.0,0.355469,0.373272,0.251152,2006,TOR,AL,1000000,13.815511
3106,zaungr01,2006,1,99,290,39,79,19,0,12,...,10.0,339.0,0.362832,0.462069,0.272414,2007,TOR,AL,3500000,15.068274
3107,zeileto01,1998,6,158,572,85,155,32,3,19,...,12.0,653.0,0.349693,0.437063,0.270979,1999,TEX,AL,3200000,14.978661
3108,zeileto01,1999,1,156,588,80,172,41,1,24,...,20.0,656.0,0.354198,0.488095,0.292517,2000,NYN,NL,4333333,15.281848
3109,zeileto01,2000,1,153,544,67,146,36,3,22,...,15.0,623.0,0.356340,0.466912,0.268382,2001,NYN,NL,6833333,15.737323
3110,zeileto01,2001,1,151,531,66,141,25,1,10,...,15.0,612.0,0.359477,0.372881,0.265537,2002,COL,NL,6833333,15.737323
3111,zeileto01,2002,1,144,506,61,138,23,0,18,...,27.0,580.0,0.353448,0.424901,0.272727,2003,NYA,AL,1500000,14.220976
3112,zeileto01,2003,3,100,299,40,68,10,2,11,...,6.0,341.0,0.307918,0.384615,0.227425,2004,NYN,NL,1000000,13.815511
3113,zobribe01,2006,1,52,183,10,41,6,2,2,...,2.0,198.0,0.260204,0.311475,0.224044,2007,TBA,AL,383400,12.856834

In [29]:
Master.groupby('playerID')['HR'].sum().sort_values(ascending=False)

playerID
rodrial01    400
sosasa01     367
ramirma02    361
bondsba01    355
delgaca01    340
thomeji01    339
guerrvl01    326
jonesan01    319
giambja01    304
jonesch06    283
heltoto01    281
palmera01    280
greensh01    276
sheffga01    275
griffke02    269
sexsori01    264
edmonji01    259
bagweje01    259
glaustr01    257
piazzmi01    251
pujolal01    250
burnije01    247
gonzalu01    247
konerpa01    245
tejadmi01    238
kentje01     238
gilesbr02    237
rolensc01    228
berkmla01    221
ortizda01    221
            ...
escobal01      1
mcguiry01      1
gutiefr01      1
mcdonja02      1
amarari01      1
joneste02      1
friasha01      1
darrmi02       1
morriha02      1
bournra01      1
baughju01      1
goodwcu01      1
berroge01      1
gotayru01      1
guilloz01      1
pauljo01       1
ojedaau01      1
fryeje01       1
nixonot01      1
strando01      0
husonje01      0
bordepa01      0
olmedra01      0
lunarfe01      0
chavera01      0
loganno01      0
ledesaa01      0
posesc01       0
tynerja01      0
gathrjo01      0
Name: HR, Length: 786, dtype: int64

# II. Building the Dataset: Player Info

In [ ]:
# Read in People data retrieved from Lahman's Database
People = pd.read_csv("../Data/People.csv")

# Read in player appearance data retrieved from Lahman's Database
Appearances = pd.read_csv("../Data/Appearances.csv")

In [ ]:
#Your Code Here

# III. Running Regressions

In [ ]:
#Your Code Here

In [ ]:
#Uncomment this cell once the assignment is complete in order to export your Master dataset
#Master.to_csv("../Data/Master.csv")