In [1]:
# This allows us to show the full screen width

from IPython.display import display, HTML

display(HTML(data="""
<style>
    div#notebook-container    { width: 95%; }
    div#menubar-container     { width: 65%; }
    div#maintoolbar-container { width: 99%; }
</style>
"""))

In [2]:
import pandas as pd
import numpy as np

In [3]:
NBAmod = pd.read_excel("Assignment Data/Week 4/NBA prediction model (Assignment).xlsx")
NBAmod

,home,visitors,day,month,year,hwinodds,hloseodds,homepts,vispts,overtime,Game(home-away),hwin,hteamsal,opposal
0,Boston Celtics,Atlanta Hawks,16,3,2019,1.16,5.59,129,120,0,Boston Celtics - Atlanta Hawks,1,126822990,83389484
1,Boston Celtics,Atlanta Hawks,15,12,2018,1.10,7.40,129,108,0,Boston Celtics - Atlanta Hawks,1,126822990,83389484
2,Brooklyn Nets,Atlanta Hawks,10,1,2019,1.25,4.13,116,100,0,Brooklyn Nets - Atlanta Hawks,1,123191458,83389484
3,Brooklyn Nets,Atlanta Hawks,16,12,2018,1.33,3.42,144,127,0,Brooklyn Nets - Atlanta Hawks,1,123191458,83389484
4,Charlotte Hornets,Atlanta Hawks,7,11,2018,1.12,6.67,113,102,0,Charlotte Hornets - Atlanta Hawks,1,115503070,83389484
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1225,Sacramento Kings,Washington Wizards,27,10,2018,2.74,1.47,116,112,0,Sacramento Kings - Washington Wizards,1,94318099,130318434
1226,San Antonio Spurs,Washington Wizards,28,1,2019,1.57,2.47,132,119,0,San Antonio Spurs - Washington Wizards,1,129760213,130318434
1227,Toronto Raptors,Washington Wizards,14,2,2019,1.20,4.76,129,120,0,Toronto Raptors - Washington Wizards,1,133823098,130318434
1228,Toronto Raptors,Washington Wizards,24,11,2018,1.17,5.32,125,107,0,Toronto Raptors - Washington Wizards,1,133823098,130318434
1229,Utah Jazz,Washington Wizards,30,3,2019,1.08,8.47,128,124,0,Utah Jazz - Washington Wizards,1,117299328,130318434

In [5]:
NBAmod['winprob']= 1/(NBAmod['hwinodds'])/(1/(NBAmod['hwinodds'])+ 1/(NBAmod['hloseodds']))
NBAmod['winpred'] = np.where(NBAmod['winprob'] >= .5,1,0)
NBAmod

,home,visitors,day,month,year,hwinodds,hloseodds,homepts,vispts,overtime,Game(home-away),hwin,hteamsal,opposal,winprob,winpred
0,Boston Celtics,Atlanta Hawks,16,3,2019,1.16,5.59,129,120,0,Boston Celtics - Atlanta Hawks,1,126822990,83389484,0.828148,1
1,Boston Celtics,Atlanta Hawks,15,12,2018,1.10,7.40,129,108,0,Boston Celtics - Atlanta Hawks,1,126822990,83389484,0.870588,1
2,Brooklyn Nets,Atlanta Hawks,10,1,2019,1.25,4.13,116,100,0,Brooklyn Nets - Atlanta Hawks,1,123191458,83389484,0.767658,1
3,Brooklyn Nets,Atlanta Hawks,16,12,2018,1.33,3.42,144,127,0,Brooklyn Nets - Atlanta Hawks,1,123191458,83389484,0.720000,1
4,Charlotte Hornets,Atlanta Hawks,7,11,2018,1.12,6.67,113,102,0,Charlotte Hornets - Atlanta Hawks,1,115503070,83389484,0.856226,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1225,Sacramento Kings,Washington Wizards,27,10,2018,2.74,1.47,116,112,0,Sacramento Kings - Washington Wizards,1,94318099,130318434,0.349169,0
1226,San Antonio Spurs,Washington Wizards,28,1,2019,1.57,2.47,132,119,0,San Antonio Spurs - Washington Wizards,1,129760213,130318434,0.611386,1
1227,Toronto Raptors,Washington Wizards,14,2,2019,1.20,4.76,129,120,0,Toronto Raptors - Washington Wizards,1,133823098,130318434,0.798658,1
1228,Toronto Raptors,Washington Wizards,24,11,2018,1.17,5.32,125,107,0,Toronto Raptors - Washington Wizards,1,133823098,130318434,0.819723,1
1229,Utah Jazz,Washington Wizards,30,3,2019,1.08,8.47,128,124,0,Utah Jazz - Washington Wizards,1,117299328,130318434,0.886911,1

In [6]:
# Taking logs of team and opponent salaries
NBAmod['lg_team_sal']=np.log(NBAmod['hteamsal'])
NBAmod['lg_opp_sal']=np.log(NBAmod['opposal'])

# taking salary ratio between two teams
NBAmod['lg_sal_ratio']= NBAmod['lg_team_sal'] - NBAmod['lg_opp_sal']
NBAmod

,home,visitors,day,month,year,hwinodds,hloseodds,homepts,vispts,overtime,Game(home-away),hwin,hteamsal,opposal,winprob,winpred,lg_team_sal,lg_opp_sal,lg_sal_ratio
0,Boston Celtics,Atlanta Hawks,16,3,2019,1.16,5.59,129,120,0,Boston Celtics - Atlanta Hawks,1,126822990,83389484,0.828148,1,18.658303,18.239033,0.419270
1,Boston Celtics,Atlanta Hawks,15,12,2018,1.10,7.40,129,108,0,Boston Celtics - Atlanta Hawks,1,126822990,83389484,0.870588,1,18.658303,18.239033,0.419270
2,Brooklyn Nets,Atlanta Hawks,10,1,2019,1.25,4.13,116,100,0,Brooklyn Nets - Atlanta Hawks,1,123191458,83389484,0.767658,1,18.629250,18.239033,0.390218
3,Brooklyn Nets,Atlanta Hawks,16,12,2018,1.33,3.42,144,127,0,Brooklyn Nets - Atlanta Hawks,1,123191458,83389484,0.720000,1,18.629250,18.239033,0.390218
4,Charlotte Hornets,Atlanta Hawks,7,11,2018,1.12,6.67,113,102,0,Charlotte Hornets - Atlanta Hawks,1,115503070,83389484,0.856226,1,18.564808,18.239033,0.325775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1225,Sacramento Kings,Washington Wizards,27,10,2018,2.74,1.47,116,112,0,Sacramento Kings - Washington Wizards,1,94318099,130318434,0.349169,0,18.362184,18.685492,-0.323308
1226,San Antonio Spurs,Washington Wizards,28,1,2019,1.57,2.47,132,119,0,San Antonio Spurs - Washington Wizards,1,129760213,130318434,0.611386,1,18.681199,18.685492,-0.004293
1227,Toronto Raptors,Washington Wizards,14,2,2019,1.20,4.76,129,120,0,Toronto Raptors - Washington Wizards,1,133823098,130318434,0.798658,1,18.712029,18.685492,0.026538
1228,Toronto Raptors,Washington Wizards,24,11,2018,1.17,5.32,125,107,0,Toronto Raptors - Washington Wizards,1,133823098,130318434,0.819723,1,18.712029,18.685492,0.026538
1229,Utah Jazz,Washington Wizards,30,3,2019,1.08,8.47,128,124,0,Utah Jazz - Washington Wizards,1,117299328,130318434,0.886911,1,18.580240,18.685492,-0.105252

In [7]:
NBA18 = NBAmod[NBAmod['year']==2018]
from sklearn.linear_model import LogisticRegression
import statsmodels.api as sm
import statsmodels.formula.api as smf
Win_lgsal = 'hwin~lg_sal_ratio'
logit_model = smf.glm(formula = Win_lgsal, data = NBA18, family=sm.families.Binomial())
result = logit_model.fit()
print(result.summary())

                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:                   hwin   No. Observations:                  542
Model:                            GLM   Df Residuals:                      540
Model Family:                Binomial   Df Model:                            1
Link Function:                  logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -359.61
Date:                Fri, 22 May 2026   Deviance:                       719.21
Time:                        10:02:01   Pearson chi2:                     543.
No. Iterations:                     4
Covariance Type:            nonrobust
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept        0.4452      0.089      5.026      0.000       0.272       0.619
lg_sal_ratio     1.1216      0.452      2.482      0.013       0.236       2.007
================================================================================

In [8]:
NBAmod['predW'] = 1/(1+np.exp(-(0.4452+1.1216*NBAmod['lg_sal_ratio'])))
NBAmod['predL'] = 1- NBAmod['predW'] 
display(NBAmod[0:10])

,home,visitors,day,month,year,hwinodds,hloseodds,homepts,vispts,overtime,...,hwin,hteamsal,opposal,winprob,winpred,lg_team_sal,lg_opp_sal,lg_sal_ratio,predW,predL
0,Boston Celtics,Atlanta Hawks,16,3,2019,1.16,5.59,129,120,0,...,1,126822990,83389484,0.828148,1,18.658303,18.239033,0.419270,0.714115,0.285885
1,Boston Celtics,Atlanta Hawks,15,12,2018,1.10,7.40,129,108,0,...,1,126822990,83389484,0.870588,1,18.658303,18.239033,0.419270,0.714115,0.285885
2,Brooklyn Nets,Atlanta Hawks,10,1,2019,1.25,4.13,116,100,0,...,1,123191458,83389484,0.767658,1,18.629250,18.239033,0.390218,0.707416,0.292584
3,Brooklyn Nets,Atlanta Hawks,16,12,2018,1.33,3.42,144,127,0,...,1,123191458,83389484,0.720000,1,18.629250,18.239033,0.390218,0.707416,0.292584
4,Charlotte Hornets,Atlanta Hawks,7,11,2018,1.12,6.67,113,102,0,...,1,115503070,83389484,0.856226,1,18.564808,18.239033,0.325775,0.692235,0.307765
5,Charlotte Hornets,Atlanta Hawks,29,11,2018,1.11,7.08,108,94,0,...,1,115503070,83389484,0.864469,1,18.564808,18.239033,0.325775,0.692235,0.307765
6,Chicago Bulls,Atlanta Hawks,3,3,2019,1.56,2.50,118,123,0,...,0,103043494,83389484,0.615764,1,18.450662,18.239033,0.211629,0.664311,0.335689
7,Chicago Bulls,Atlanta Hawks,24,1,2019,1.83,2.02,101,121,0,...,0,103043494,83389484,0.524675,1,18.450662,18.239033,0.211629,0.664311,0.335689
8,Cleveland Cavaliers,Atlanta Hawks,22,10,2018,1.26,3.97,111,133,0,...,0,125587784,83389484,0.759082,1,18.648516,18.239033,0.409483,0.711868,0.288132
9,Cleveland Cavaliers,Atlanta Hawks,31,10,2018,1.49,2.71,136,114,0,...,1,125587784,83389484,0.645238,1,18.648516,18.239033,0.409483,0.711868,0.288132

In [10]:
NBAmod.loc[NBAmod.predL > NBAmod.predW, 'fitted'] = 0
NBAmod.loc[NBAmod.predW > NBAmod.predL, 'fitted'] = 1
NBAmod

,home,visitors,day,month,year,hwinodds,hloseodds,homepts,vispts,overtime,...,hteamsal,opposal,winprob,winpred,lg_team_sal,lg_opp_sal,lg_sal_ratio,predW,predL,fitted
0,Boston Celtics,Atlanta Hawks,16,3,2019,1.16,5.59,129,120,0,...,126822990,83389484,0.828148,1,18.658303,18.239033,0.419270,0.714115,0.285885,1
1,Boston Celtics,Atlanta Hawks,15,12,2018,1.10,7.40,129,108,0,...,126822990,83389484,0.870588,1,18.658303,18.239033,0.419270,0.714115,0.285885,1
2,Brooklyn Nets,Atlanta Hawks,10,1,2019,1.25,4.13,116,100,0,...,123191458,83389484,0.767658,1,18.629250,18.239033,0.390218,0.707416,0.292584,1
3,Brooklyn Nets,Atlanta Hawks,16,12,2018,1.33,3.42,144,127,0,...,123191458,83389484,0.720000,1,18.629250,18.239033,0.390218,0.707416,0.292584,1
4,Charlotte Hornets,Atlanta Hawks,7,11,2018,1.12,6.67,113,102,0,...,115503070,83389484,0.856226,1,18.564808,18.239033,0.325775,0.692235,0.307765,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1225,Sacramento Kings,Washington Wizards,27,10,2018,2.74,1.47,116,112,0,...,94318099,130318434,0.349169,0,18.362184,18.685492,-0.323308,0.520633,0.479367,1
1226,San Antonio Spurs,Washington Wizards,28,1,2019,1.57,2.47,132,119,0,...,129760213,130318434,0.611386,1,18.681199,18.685492,-0.004293,0.608351,0.391649,1
1227,Toronto Raptors,Washington Wizards,14,2,2019,1.20,4.76,129,120,0,...,133823098,130318434,0.798658,1,18.712029,18.685492,0.026538,0.616558,0.383442,1
1228,Toronto Raptors,Washington Wizards,24,11,2018,1.17,5.32,125,107,0,...,133823098,130318434,0.819723,1,18.712029,18.685492,0.026538,0.616558,0.383442,1
1229,Utah Jazz,Washington Wizards,30,3,2019,1.08,8.47,128,124,0,...,117299328,130318434,0.886911,1,18.580240,18.685492,-0.105252,0.581066,0.418934,1

In [11]:
NBA19 = NBAmod[NBAmod['year']==2019]
NBA19['TRUE_odds'] = np.where(NBA19['winpred']==NBA19['hwin'], 1, 0)
NBA19['TRUE_logit'] = np.where(NBA19['fitted']==NBA19['hwin'], 1, 0)
display(NBA19[0:10])

,home,visitors,day,month,year,hwinodds,hloseodds,homepts,vispts,overtime,...,winprob,winpred,lg_team_sal,lg_opp_sal,lg_sal_ratio,predW,predL,fitted,TRUE_odds,TRUE_logit
0,Boston Celtics,Atlanta Hawks,16,3,2019,1.16,5.59,129,120,0,...,0.828148,1,18.658303,18.239033,0.419270,0.714115,0.285885,1,1,1
2,Brooklyn Nets,Atlanta Hawks,10,1,2019,1.25,4.13,116,100,0,...,0.767658,1,18.629250,18.239033,0.390218,0.707416,0.292584,1,1,1
6,Chicago Bulls,Atlanta Hawks,3,3,2019,1.56,2.50,118,123,0,...,0.615764,1,18.450662,18.239033,0.211629,0.664311,0.335689,1,0,0
7,Chicago Bulls,Atlanta Hawks,24,1,2019,1.83,2.02,101,121,0,...,0.524675,1,18.450662,18.239033,0.211629,0.664311,0.335689,1,0,0
14,Houston Rockets,Atlanta Hawks,26,2,2019,1.09,7.99,119,111,0,...,0.879956,1,18.715174,18.239033,0.476141,0.726957,0.273043,1,1,1
17,Los Angeles Clippers,Atlanta Hawks,29,1,2019,1.40,3.06,118,123,0,...,0.686099,1,18.569651,18.239033,0.330618,0.693391,0.306609,1,0,0
20,Miami Heat,Atlanta Hawks,5,3,2019,1.18,5.22,114,113,0,...,0.815625,1,18.879787,18.239033,0.640754,0.762035,0.237965,1,1,1
22,Milwaukee Bucks,Atlanta Hawks,8,4,2019,1.12,6.74,115,107,0,...,0.857506,1,18.549553,18.239033,0.310521,0.688578,0.311422,1,1,1
23,Milwaukee Bucks,Atlanta Hawks,5,1,2019,1.09,8.24,144,112,0,...,0.883173,1,18.549553,18.239033,0.310521,0.688578,0.311422,1,1,1
25,New Orleans Pelicans,Atlanta Hawks,27,3,2019,2.18,1.72,120,130,0,...,0.441026,0,18.564213,18.239033,0.325180,0.692093,0.307907,1,1,0

In [12]:
NBA19['TRUE_odds'].mean()

0.6918604651162791

In [13]:
NBA19['TRUE_logit'].mean()

0.5872093023255814

In [14]:
NBA19

,home,visitors,day,month,year,hwinodds,hloseodds,homepts,vispts,overtime,...,winprob,winpred,lg_team_sal,lg_opp_sal,lg_sal_ratio,predW,predL,fitted,TRUE_odds,TRUE_logit
0,Boston Celtics,Atlanta Hawks,16,3,2019,1.16,5.59,129,120,0,...,0.828148,1,18.658303,18.239033,0.419270,0.714115,0.285885,1,1,1
2,Brooklyn Nets,Atlanta Hawks,10,1,2019,1.25,4.13,116,100,0,...,0.767658,1,18.629250,18.239033,0.390218,0.707416,0.292584,1,1,1
6,Chicago Bulls,Atlanta Hawks,3,3,2019,1.56,2.50,118,123,0,...,0.615764,1,18.450662,18.239033,0.211629,0.664311,0.335689,1,0,0
7,Chicago Bulls,Atlanta Hawks,24,1,2019,1.83,2.02,101,121,0,...,0.524675,1,18.450662,18.239033,0.211629,0.664311,0.335689,1,0,0
14,Houston Rockets,Atlanta Hawks,26,2,2019,1.09,7.99,119,111,0,...,0.879956,1,18.715174,18.239033,0.476141,0.726957,0.273043,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1221,Philadelphia 76ers,Washington Wizards,9,1,2019,1.28,3.80,132,115,0,...,0.748031,1,18.475256,18.685492,-0.210236,0.552159,0.447841,1,1,1
1223,Phoenix Suns,Washington Wizards,28,3,2019,2.00,1.85,121,124,0,...,0.480519,0,18.455989,18.685492,-0.229503,0.546810,0.453190,1,1,0
1226,San Antonio Spurs,Washington Wizards,28,1,2019,1.57,2.47,132,119,0,...,0.611386,1,18.681199,18.685492,-0.004293,0.608351,0.391649,1,1,1
1227,Toronto Raptors,Washington Wizards,14,2,2019,1.20,4.76,129,120,0,...,0.798658,1,18.712029,18.685492,0.026538,0.616558,0.383442,1,1,1
1229,Utah Jazz,Washington Wizards,30,3,2019,1.08,8.47,128,124,0,...,0.886911,1,18.580240,18.685492,-0.105252,0.581066,0.418934,1,1,1

In [16]:
NBA19['Toutcome'] = np.where(NBA19['hwin'] == 1, 1,0)
NBA19['Ooutcome'] = np.where(NBA19['hwin'] == 0, 1,0)
BrierLogit = ((NBA19['predW'] - NBA19['Toutcome'])**2 + (NBA19['predL'] - NBA19['Ooutcome'])**2).sum()/688

BrierLogit

0.47687134114270785

In [17]:
BrierOdds = ((NBA19['winprob'] - NBA19['Toutcome'])**2 + ((1-NBA19['winprob']) - NBA19['Ooutcome'])**2).sum()/688

BrierOdds

0.3939058021238843

In [18]:
NBA18

,home,visitors,day,month,year,hwinodds,hloseodds,homepts,vispts,overtime,Game(home-away),hwin,hteamsal,opposal,winprob,winpred,lg_team_sal,lg_opp_sal,lg_sal_ratio
1,Boston Celtics,Atlanta Hawks,15,12,2018,1.10,7.40,129,108,0,Boston Celtics - Atlanta Hawks,1,126822990,83389484,0.870588,1,18.658303,18.239033,0.419270
3,Brooklyn Nets,Atlanta Hawks,16,12,2018,1.33,3.42,144,127,0,Brooklyn Nets - Atlanta Hawks,1,123191458,83389484,0.720000,1,18.629250,18.239033,0.390218
4,Charlotte Hornets,Atlanta Hawks,7,11,2018,1.12,6.67,113,102,0,Charlotte Hornets - Atlanta Hawks,1,115503070,83389484,0.856226,1,18.564808,18.239033,0.325775
5,Charlotte Hornets,Atlanta Hawks,29,11,2018,1.11,7.08,108,94,0,Charlotte Hornets - Atlanta Hawks,1,115503070,83389484,0.864469,1,18.564808,18.239033,0.325775
8,Cleveland Cavaliers,Atlanta Hawks,22,10,2018,1.26,3.97,111,133,0,Cleveland Cavaliers - Atlanta Hawks,0,125587784,83389484,0.759082,1,18.648516,18.239033,0.409483
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1220,Orlando Magic,Washington Wizards,10,11,2018,2.46,1.58,117,108,0,Orlando Magic - Washington Wizards,1,107918996,130318434,0.391089,0,18.496891,18.685492,-0.188600
1222,Philadelphia 76ers,Washington Wizards,1,12,2018,1.23,4.27,123,98,0,Philadelphia 76ers - Washington Wizards,1,105609165,130318434,0.776364,1,18.475256,18.685492,-0.210236
1224,Portland Trail Blazers,Washington Wizards,23,10,2018,1.51,2.65,124,125,1,Portland Trail Blazers - Washington Wizards,0,131666204,130318434,0.637019,1,18.695781,18.685492,0.010289
1225,Sacramento Kings,Washington Wizards,27,10,2018,2.74,1.47,116,112,0,Sacramento Kings - Washington Wizards,1,94318099,130318434,0.349169,0,18.362184,18.685492,-0.323308
1228,Toronto Raptors,Washington Wizards,24,11,2018,1.17,5.32,125,107,0,Toronto Raptors - Washington Wizards,1,133823098,130318434,0.819723,1,18.712029,18.685492,0.026538