In [1]:
# This allows us to show the full screen width

from IPython.display import display, HTML

display(HTML(data="""
<style>
    div#notebook-container    { width: 95%; }
    div#menubar-container     { width: 65%; }
    div#maintoolbar-container { width: 99%; }
</style>
"""))

In [2]:
import pandas as pd
import numpy as np

In [3]:
BLmod = pd.read_excel("Assignment Data/Week 3/Bundesliga prediction model (Assignment).xlsx")
BLmod

,Date,gameno,day,month,year,HomeTeam,AwayTeam,FTHG,FTAG,FTR,B365H,B365D,B365A,Tmhome,Tmaway
0,16/08/2019,1,16,8,2019,Bayern Munich,Hertha,2,2,D,1.14,8.00,15.00,116.05,215.20
1,17/08/2019,2,17,8,2019,Dortmund,Augsburg,5,1,H,1.20,7.00,13.00,790.40,116.05
2,17/08/2019,3,17,8,2019,Wolfsburg,FC Koln,2,1,H,1.95,3.50,4.00,162.28,101.10
3,17/08/2019,4,17,8,2019,Werder Bremen,Fortuna Dusseldorf,1,3,A,1.75,3.75,4.75,35.58,81.65
4,17/08/2019,5,17,8,2019,Freiburg,Mainz,3,0,H,2.25,3.25,3.40,81.65,148.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,27/06/2020,302,27,6,2020,Dortmund,Hoffenheim,0,4,A,1.70,4.50,4.10,642.10,229.50
302,27/06/2020,303,27,6,2020,Leverkusen,Mainz,1,0,H,1.25,6.50,10.00,420.60,148.60
303,27/06/2020,304,27,6,2020,Ein Frankfurt,Paderborn,3,2,H,1.30,5.75,9.00,207.55,24.10
304,27/06/2020,305,27,6,2020,Augsburg,RB Leipzig,1,2,A,7.00,5.75,1.36,116.05,521.90
305,27/06/2020,306,27,6,2020,Freiburg,Schalke 04,4,0,H,1.80,4.00,4.20,113.98,213.48

In [4]:
BLmod['B365HPr']= 1/(BLmod['B365H'])/(1/(BLmod['B365H'])+ 1/(BLmod['B365D'])+ 1/(BLmod['B365A']))
BLmod['B365DPr']= 1/(BLmod['B365D'])/(1/(BLmod['B365H'])+ 1/(BLmod['B365D'])+ 1/(BLmod['B365A']))
BLmod['B365APr']= 1/(BLmod['B365A'])/(1/(BLmod['B365H'])+ 1/(BLmod['B365D'])+ 1/(BLmod['B365A']))
BLmod

,Date,gameno,day,month,year,HomeTeam,AwayTeam,FTHG,FTAG,FTR,B365H,B365D,B365A,Tmhome,Tmaway,B365HPr,B365DPr,B365APr
0,16/08/2019,1,16,8,2019,Bayern Munich,Hertha,2,2,D,1.14,8.00,15.00,116.05,215.20,0.820681,0.116947,0.062372
1,17/08/2019,2,17,8,2019,Dortmund,Augsburg,5,1,H,1.20,7.00,13.00,790.40,116.05,0.791304,0.135652,0.073043
2,17/08/2019,3,17,8,2019,Wolfsburg,FC Koln,2,1,H,1.95,3.50,4.00,162.28,101.10,0.489083,0.272489,0.238428
3,17/08/2019,4,17,8,2019,Werder Bremen,Fortuna Dusseldorf,1,3,A,1.75,3.75,4.75,35.58,81.65,0.544933,0.254302,0.200765
4,17/08/2019,5,17,8,2019,Freiburg,Mainz,3,0,H,2.25,3.25,3.40,81.65,148.60,0.424796,0.294089,0.281115
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,27/06/2020,302,27,6,2020,Dortmund,Hoffenheim,0,4,A,1.70,4.50,4.10,642.10,229.50,0.557907,0.210765,0.231327
302,27/06/2020,303,27,6,2020,Leverkusen,Mainz,1,0,H,1.25,6.50,10.00,420.60,148.60,0.759124,0.145985,0.094891
303,27/06/2020,304,27,6,2020,Ein Frankfurt,Paderborn,3,2,H,1.30,5.75,9.00,207.55,24.10,0.729644,0.164963,0.105393
304,27/06/2020,305,27,6,2020,Augsburg,RB Leipzig,1,2,A,7.00,5.75,1.36,116.05,521.90,0.135787,0.165306,0.698906
305,27/06/2020,306,27,6,2020,Freiburg,Schalke 04,4,0,H,1.80,4.00,4.20,113.98,213.48,0.532319,0.239544,0.228137

In [5]:
BLmod['B365res']= np.where((BLmod['B365HPr']>BLmod['B365DPr']) & (BLmod['B365HPr']>BLmod['B365APr']),'H',\
                            np.where((BLmod['B365DPr']>BLmod['B365HPr']) & (BLmod['B365DPr']>BLmod['B365APr']),'D','A'))
BLmod

,Date,gameno,day,month,year,HomeTeam,AwayTeam,FTHG,FTAG,FTR,B365H,B365D,B365A,Tmhome,Tmaway,B365HPr,B365DPr,B365APr,B365res
0,16/08/2019,1,16,8,2019,Bayern Munich,Hertha,2,2,D,1.14,8.00,15.00,116.05,215.20,0.820681,0.116947,0.062372,H
1,17/08/2019,2,17,8,2019,Dortmund,Augsburg,5,1,H,1.20,7.00,13.00,790.40,116.05,0.791304,0.135652,0.073043,H
2,17/08/2019,3,17,8,2019,Wolfsburg,FC Koln,2,1,H,1.95,3.50,4.00,162.28,101.10,0.489083,0.272489,0.238428,H
3,17/08/2019,4,17,8,2019,Werder Bremen,Fortuna Dusseldorf,1,3,A,1.75,3.75,4.75,35.58,81.65,0.544933,0.254302,0.200765,H
4,17/08/2019,5,17,8,2019,Freiburg,Mainz,3,0,H,2.25,3.25,3.40,81.65,148.60,0.424796,0.294089,0.281115,H
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,27/06/2020,302,27,6,2020,Dortmund,Hoffenheim,0,4,A,1.70,4.50,4.10,642.10,229.50,0.557907,0.210765,0.231327,H
302,27/06/2020,303,27,6,2020,Leverkusen,Mainz,1,0,H,1.25,6.50,10.00,420.60,148.60,0.759124,0.145985,0.094891,H
303,27/06/2020,304,27,6,2020,Ein Frankfurt,Paderborn,3,2,H,1.30,5.75,9.00,207.55,24.10,0.729644,0.164963,0.105393,H
304,27/06/2020,305,27,6,2020,Augsburg,RB Leipzig,1,2,A,7.00,5.75,1.36,116.05,521.90,0.135787,0.165306,0.698906,A
305,27/06/2020,306,27,6,2020,Freiburg,Schalke 04,4,0,H,1.80,4.00,4.20,113.98,213.48,0.532319,0.239544,0.228137,H

In [6]:
BLmod['winvalue'] = np.where(BLmod['FTR'] == 'H', 2 ,(np.where(BLmod['FTR'] == 'D', 1, 0)))
BLmod

,Date,gameno,day,month,year,HomeTeam,AwayTeam,FTHG,FTAG,FTR,B365H,B365D,B365A,Tmhome,Tmaway,B365HPr,B365DPr,B365APr,B365res,winvalue
0,16/08/2019,1,16,8,2019,Bayern Munich,Hertha,2,2,D,1.14,8.00,15.00,116.05,215.20,0.820681,0.116947,0.062372,H,1
1,17/08/2019,2,17,8,2019,Dortmund,Augsburg,5,1,H,1.20,7.00,13.00,790.40,116.05,0.791304,0.135652,0.073043,H,2
2,17/08/2019,3,17,8,2019,Wolfsburg,FC Koln,2,1,H,1.95,3.50,4.00,162.28,101.10,0.489083,0.272489,0.238428,H,2
3,17/08/2019,4,17,8,2019,Werder Bremen,Fortuna Dusseldorf,1,3,A,1.75,3.75,4.75,35.58,81.65,0.544933,0.254302,0.200765,H,0
4,17/08/2019,5,17,8,2019,Freiburg,Mainz,3,0,H,2.25,3.25,3.40,81.65,148.60,0.424796,0.294089,0.281115,H,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,27/06/2020,302,27,6,2020,Dortmund,Hoffenheim,0,4,A,1.70,4.50,4.10,642.10,229.50,0.557907,0.210765,0.231327,H,0
302,27/06/2020,303,27,6,2020,Leverkusen,Mainz,1,0,H,1.25,6.50,10.00,420.60,148.60,0.759124,0.145985,0.094891,H,2
303,27/06/2020,304,27,6,2020,Ein Frankfurt,Paderborn,3,2,H,1.30,5.75,9.00,207.55,24.10,0.729644,0.164963,0.105393,H,2
304,27/06/2020,305,27,6,2020,Augsburg,RB Leipzig,1,2,A,7.00,5.75,1.36,116.05,521.90,0.135787,0.165306,0.698906,A,0
305,27/06/2020,306,27,6,2020,Freiburg,Schalke 04,4,0,H,1.80,4.00,4.20,113.98,213.48,0.532319,0.239544,0.228137,H,2

In [7]:
pd.crosstab(BLmod['FTR'], BLmod['B365res'],dropna= True)

B365res   A   H
FTR
A        63  52
D        18  50
H        28  95

In [9]:
BLmod['lhTMratio'] = np.log(BLmod['Tmhome']/BLmod['Tmaway'])
BLmod

,Date,gameno,day,month,year,HomeTeam,AwayTeam,FTHG,FTAG,FTR,...,B365D,B365A,Tmhome,Tmaway,B365HPr,B365DPr,B365APr,B365res,winvalue,lhTMratio
0,16/08/2019,1,16,8,2019,Bayern Munich,Hertha,2,2,D,...,8.00,15.00,116.05,215.20,0.820681,0.116947,0.062372,H,1,-0.617547
1,17/08/2019,2,17,8,2019,Dortmund,Augsburg,5,1,H,...,7.00,13.00,790.40,116.05,0.791304,0.135652,0.073043,H,2,1.918518
2,17/08/2019,3,17,8,2019,Wolfsburg,FC Koln,2,1,H,...,3.50,4.00,162.28,101.10,0.489083,0.272489,0.238428,H,2,0.473213
3,17/08/2019,4,17,8,2019,Werder Bremen,Fortuna Dusseldorf,1,3,A,...,3.75,4.75,35.58,81.65,0.544933,0.254302,0.200765,H,0,-0.830658
4,17/08/2019,5,17,8,2019,Freiburg,Mainz,3,0,H,...,3.25,3.40,81.65,148.60,0.424796,0.294089,0.281115,H,2,-0.598816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,27/06/2020,302,27,6,2020,Dortmund,Hoffenheim,0,4,A,...,4.50,4.10,642.10,229.50,0.557907,0.210765,0.231327,H,0,1.028841
302,27/06/2020,303,27,6,2020,Leverkusen,Mainz,1,0,H,...,6.50,10.00,420.60,148.60,0.759124,0.145985,0.094891,H,2,1.040424
303,27/06/2020,304,27,6,2020,Ein Frankfurt,Paderborn,3,2,H,...,5.75,9.00,207.55,24.10,0.729644,0.164963,0.105393,H,2,2.153160
304,27/06/2020,305,27,6,2020,Augsburg,RB Leipzig,1,2,A,...,5.75,1.36,116.05,521.90,0.135787,0.165306,0.698906,A,0,-1.503455
305,27/06/2020,306,27,6,2020,Freiburg,Schalke 04,4,0,H,...,4.00,4.20,113.98,213.48,0.532319,0.239544,0.228137,H,2,-0.627520

In [10]:
season19 = BLmod[:224]
season19

,Date,gameno,day,month,year,HomeTeam,AwayTeam,FTHG,FTAG,FTR,...,B365D,B365A,Tmhome,Tmaway,B365HPr,B365DPr,B365APr,B365res,winvalue,lhTMratio
0,16/08/2019,1,16,8,2019,Bayern Munich,Hertha,2,2,D,...,8.00,15.00,116.05,215.20,0.820681,0.116947,0.062372,H,1,-0.617547
1,17/08/2019,2,17,8,2019,Dortmund,Augsburg,5,1,H,...,7.00,13.00,790.40,116.05,0.791304,0.135652,0.073043,H,2,1.918518
2,17/08/2019,3,17,8,2019,Wolfsburg,FC Koln,2,1,H,...,3.50,4.00,162.28,101.10,0.489083,0.272489,0.238428,H,2,0.473213
3,17/08/2019,4,17,8,2019,Werder Bremen,Fortuna Dusseldorf,1,3,A,...,3.75,4.75,35.58,81.65,0.544933,0.254302,0.200765,H,0,-0.830658
4,17/08/2019,5,17,8,2019,Freiburg,Mainz,3,0,H,...,3.25,3.40,81.65,148.60,0.424796,0.294089,0.281115,H,2,-0.598816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,2020-07-03 00:00:00,220,7,3,2020,Freiburg,Union Berlin,3,1,H,...,3.40,3.10,113.98,35.58,0.413495,0.279718,0.306787,H,2,1.164239
220,2020-07-03 00:00:00,221,7,3,2020,Hertha,Werder Bremen,2,2,D,...,3.50,3.40,215.20,162.28,0.450928,0.270557,0.278515,H,1,0.282245
221,2020-08-03 00:00:00,222,8,3,2020,Bayern Munich,Augsburg,2,0,H,...,10.00,21.00,790.40,116.05,0.859212,0.095373,0.045415,H,2,1.918518
222,2020-08-03 00:00:00,223,8,3,2020,Mainz,Fortuna Dusseldorf,1,1,D,...,3.75,3.80,148.60,81.65,0.498339,0.252492,0.249169,H,1,0.598816
223,2020-11-03 00:00:00,224,11,3,2020,M'gladbach,FC Koln,2,1,H,...,4.00,4.20,266.50,101.10,0.543619,0.233756,0.222625,H,2,0.969264

In [11]:
from bevel.linear_ordinal_regression import OrderedLogit
ol = OrderedLogit()

In [12]:
ol.fit(season19['lhTMratio'], season19['winvalue'])
ol.print_summary()

n=224
                  beta  se(beta)      p  lower 0.95  upper 0.95
attribute names
column_1        0.5981    0.1129 0.0000      0.3769      0.8193  ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Somers' D = 0.278

In [13]:
# Predicted probabilities

BLmod['predA'] = 1/(1+np.exp(-(ol.coef_[1]-ol.coef_[0]*BLmod['lhTMratio'])))
BLmod['predD'] = 1/(1+np.exp(-(ol.coef_[2]-ol.coef_[0]*BLmod['lhTMratio']))) - BLmod['predA']
BLmod['predH'] = 1 - BLmod['predA'] - BLmod['predD']

pd.set_option('display.max_columns', 50)
BLmod

,Date,gameno,day,month,year,HomeTeam,AwayTeam,FTHG,FTAG,FTR,B365H,B365D,B365A,Tmhome,Tmaway,B365HPr,B365DPr,B365APr,B365res,winvalue,lhTMratio,predA,predD,predH
0,16/08/2019,1,16,8,2019,Bayern Munich,Hertha,2,2,D,1.14,8.00,15.00,116.05,215.20,0.820681,0.116947,0.062372,H,1,-0.617547,0.424580,0.244701,0.330720
1,17/08/2019,2,17,8,2019,Dortmund,Augsburg,5,1,H,1.20,7.00,13.00,790.40,116.05,0.791304,0.135652,0.073043,H,2,1.918518,0.139329,0.168148,0.692524
2,17/08/2019,3,17,8,2019,Wolfsburg,FC Koln,2,1,H,1.95,3.50,4.00,162.28,101.10,0.489083,0.272489,0.238428,H,2,0.473213,0.277598,0.235530,0.486872
3,17/08/2019,4,17,8,2019,Werder Bremen,Fortuna Dusseldorf,1,3,A,1.75,3.75,4.75,35.58,81.65,0.544933,0.254302,0.200765,H,0,-0.830658,0.455981,0.240881,0.303138
4,17/08/2019,5,17,8,2019,Freiburg,Mainz,3,0,H,2.25,3.25,3.40,81.65,148.60,0.424796,0.294089,0.281115,H,2,-0.598816,0.421845,0.244951,0.333204
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,27/06/2020,302,27,6,2020,Dortmund,Hoffenheim,0,4,A,1.70,4.50,4.10,642.10,229.50,0.557907,0.210765,0.231327,H,0,1.028841,0.216066,0.214435,0.569499
302,27/06/2020,303,27,6,2020,Leverkusen,Mainz,1,0,H,1.25,6.50,10.00,420.60,148.60,0.759124,0.145985,0.094891,H,2,1.040424,0.214895,0.213908,0.571197
303,27/06/2020,304,27,6,2020,Ein Frankfurt,Paderborn,3,2,H,1.30,5.75,9.00,207.55,24.10,0.729644,0.164963,0.105393,H,2,2.153160,0.123335,0.155090,0.721575
304,27/06/2020,305,27,6,2020,Augsburg,RB Leipzig,1,2,A,7.00,5.75,1.36,116.05,521.90,0.135787,0.165306,0.698906,A,0,-1.503455,0.556231,0.218429,0.225340
305,27/06/2020,306,27,6,2020,Freiburg,Schalke 04,4,0,H,1.80,4.00,4.20,113.98,213.48,0.532319,0.239544,0.228137,H,2,-0.627520,0.426038,0.244562,0.329401

In [14]:
# Result prediction

BLmod['Maxprob'] =BLmod[['predA','predD','predH']].max(axis=1)
BLmod['logitpred']=np.where(BLmod['Maxprob']==BLmod['predA'],'A',\
                               np.where(BLmod['Maxprob']==BLmod['predD'],'D','H'))
BLmod['logittrue']= np.where(BLmod['logitpred'] == BLmod['FTR'],1,0)
BLmod

,Date,gameno,day,month,year,HomeTeam,AwayTeam,FTHG,FTAG,FTR,B365H,B365D,B365A,Tmhome,Tmaway,B365HPr,B365DPr,B365APr,B365res,winvalue,lhTMratio,predA,predD,predH,Maxprob,logitpred,logittrue
0,16/08/2019,1,16,8,2019,Bayern Munich,Hertha,2,2,D,1.14,8.00,15.00,116.05,215.20,0.820681,0.116947,0.062372,H,1,-0.617547,0.424580,0.244701,0.330720,0.424580,A,0
1,17/08/2019,2,17,8,2019,Dortmund,Augsburg,5,1,H,1.20,7.00,13.00,790.40,116.05,0.791304,0.135652,0.073043,H,2,1.918518,0.139329,0.168148,0.692524,0.692524,H,1
2,17/08/2019,3,17,8,2019,Wolfsburg,FC Koln,2,1,H,1.95,3.50,4.00,162.28,101.10,0.489083,0.272489,0.238428,H,2,0.473213,0.277598,0.235530,0.486872,0.486872,H,1
3,17/08/2019,4,17,8,2019,Werder Bremen,Fortuna Dusseldorf,1,3,A,1.75,3.75,4.75,35.58,81.65,0.544933,0.254302,0.200765,H,0,-0.830658,0.455981,0.240881,0.303138,0.455981,A,1
4,17/08/2019,5,17,8,2019,Freiburg,Mainz,3,0,H,2.25,3.25,3.40,81.65,148.60,0.424796,0.294089,0.281115,H,2,-0.598816,0.421845,0.244951,0.333204,0.421845,A,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,27/06/2020,302,27,6,2020,Dortmund,Hoffenheim,0,4,A,1.70,4.50,4.10,642.10,229.50,0.557907,0.210765,0.231327,H,0,1.028841,0.216066,0.214435,0.569499,0.569499,H,0
302,27/06/2020,303,27,6,2020,Leverkusen,Mainz,1,0,H,1.25,6.50,10.00,420.60,148.60,0.759124,0.145985,0.094891,H,2,1.040424,0.214895,0.213908,0.571197,0.571197,H,1
303,27/06/2020,304,27,6,2020,Ein Frankfurt,Paderborn,3,2,H,1.30,5.75,9.00,207.55,24.10,0.729644,0.164963,0.105393,H,2,2.153160,0.123335,0.155090,0.721575,0.721575,H,1
304,27/06/2020,305,27,6,2020,Augsburg,RB Leipzig,1,2,A,7.00,5.75,1.36,116.05,521.90,0.135787,0.165306,0.698906,A,0,-1.503455,0.556231,0.218429,0.225340,0.556231,A,1
305,27/06/2020,306,27,6,2020,Freiburg,Schalke 04,4,0,H,1.80,4.00,4.20,113.98,213.48,0.532319,0.239544,0.228137,H,2,-0.627520,0.426038,0.244562,0.329401,0.426038,A,0

In [17]:
trunc19_20 = BLmod[224:].copy()
trunc19_20

,Date,gameno,day,month,year,HomeTeam,AwayTeam,FTHG,FTAG,FTR,B365H,B365D,B365A,Tmhome,Tmaway,B365HPr,B365DPr,B365APr,B365res,winvalue,lhTMratio,predA,predD,predH,Maxprob,logitpred,logittrue
224,16/05/2020,225,16,5,2020,RB Leipzig,Freiburg,1,1,D,1.30,5.50,9.00,521.90,113.98,0.724214,0.171178,0.104609,H,1,1.521453,0.170317,0.189894,0.639790,0.639790,H,0
225,16/05/2020,226,16,5,2020,Hoffenheim,Hertha,0,3,A,2.10,3.60,3.20,229.50,215.20,0.446512,0.260465,0.293023,H,0,0.064335,0.329190,0.244539,0.426271,0.426271,H,0
226,16/05/2020,227,16,5,2020,Ein Frankfurt,M'gladbach,1,3,A,2.90,3.60,2.25,207.55,266.50,0.323160,0.260323,0.416517,A,0,-0.250002,0.371955,0.246995,0.381050,0.381050,H,0
227,16/05/2020,228,16,5,2020,Fortuna Dusseldorf,Paderborn,0,0,D,2.10,3.60,3.25,81.65,24.10,0.448534,0.261645,0.289822,H,1,1.220230,0.197306,0.205380,0.597313,0.597313,H,0
228,16/05/2020,229,16,5,2020,Dortmund,Schalke 04,4,0,H,1.50,4.33,6.00,642.10,213.48,0.626401,0.216998,0.156600,H,2,1.101201,0.208825,0.211098,0.580077,0.580077,H,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,27/06/2020,302,27,6,2020,Dortmund,Hoffenheim,0,4,A,1.70,4.50,4.10,642.10,229.50,0.557907,0.210765,0.231327,H,0,1.028841,0.216066,0.214435,0.569499,0.569499,H,0
302,27/06/2020,303,27,6,2020,Leverkusen,Mainz,1,0,H,1.25,6.50,10.00,420.60,148.60,0.759124,0.145985,0.094891,H,2,1.040424,0.214895,0.213908,0.571197,0.571197,H,1
303,27/06/2020,304,27,6,2020,Ein Frankfurt,Paderborn,3,2,H,1.30,5.75,9.00,207.55,24.10,0.729644,0.164963,0.105393,H,2,2.153160,0.123335,0.155090,0.721575,0.721575,H,1
304,27/06/2020,305,27,6,2020,Augsburg,RB Leipzig,1,2,A,7.00,5.75,1.36,116.05,521.90,0.135787,0.165306,0.698906,A,0,-1.503455,0.556231,0.218429,0.225340,0.556231,A,1
305,27/06/2020,306,27,6,2020,Freiburg,Schalke 04,4,0,H,1.80,4.00,4.20,113.98,213.48,0.532319,0.239544,0.228137,H,2,-0.627520,0.426038,0.244562,0.329401,0.426038,A,0

In [18]:
trunc19_20['B365true']= np.where(trunc19_20['B365res'] == trunc19_20['FTR'],1,0)
trunc19_20

,Date,gameno,day,month,year,HomeTeam,AwayTeam,FTHG,FTAG,FTR,B365H,B365D,B365A,Tmhome,Tmaway,B365HPr,B365DPr,B365APr,B365res,winvalue,lhTMratio,predA,predD,predH,Maxprob,logitpred,logittrue,B365true
224,16/05/2020,225,16,5,2020,RB Leipzig,Freiburg,1,1,D,1.30,5.50,9.00,521.90,113.98,0.724214,0.171178,0.104609,H,1,1.521453,0.170317,0.189894,0.639790,0.639790,H,0,0
225,16/05/2020,226,16,5,2020,Hoffenheim,Hertha,0,3,A,2.10,3.60,3.20,229.50,215.20,0.446512,0.260465,0.293023,H,0,0.064335,0.329190,0.244539,0.426271,0.426271,H,0,0
226,16/05/2020,227,16,5,2020,Ein Frankfurt,M'gladbach,1,3,A,2.90,3.60,2.25,207.55,266.50,0.323160,0.260323,0.416517,A,0,-0.250002,0.371955,0.246995,0.381050,0.381050,H,0,1
227,16/05/2020,228,16,5,2020,Fortuna Dusseldorf,Paderborn,0,0,D,2.10,3.60,3.25,81.65,24.10,0.448534,0.261645,0.289822,H,1,1.220230,0.197306,0.205380,0.597313,0.597313,H,0,0
228,16/05/2020,229,16,5,2020,Dortmund,Schalke 04,4,0,H,1.50,4.33,6.00,642.10,213.48,0.626401,0.216998,0.156600,H,2,1.101201,0.208825,0.211098,0.580077,0.580077,H,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,27/06/2020,302,27,6,2020,Dortmund,Hoffenheim,0,4,A,1.70,4.50,4.10,642.10,229.50,0.557907,0.210765,0.231327,H,0,1.028841,0.216066,0.214435,0.569499,0.569499,H,0,0
302,27/06/2020,303,27,6,2020,Leverkusen,Mainz,1,0,H,1.25,6.50,10.00,420.60,148.60,0.759124,0.145985,0.094891,H,2,1.040424,0.214895,0.213908,0.571197,0.571197,H,1,1
303,27/06/2020,304,27,6,2020,Ein Frankfurt,Paderborn,3,2,H,1.30,5.75,9.00,207.55,24.10,0.729644,0.164963,0.105393,H,2,2.153160,0.123335,0.155090,0.721575,0.721575,H,1,1
304,27/06/2020,305,27,6,2020,Augsburg,RB Leipzig,1,2,A,7.00,5.75,1.36,116.05,521.90,0.135787,0.165306,0.698906,A,0,-1.503455,0.556231,0.218429,0.225340,0.556231,A,1,1
305,27/06/2020,306,27,6,2020,Freiburg,Schalke 04,4,0,H,1.80,4.00,4.20,113.98,213.48,0.532319,0.239544,0.228137,H,2,-0.627520,0.426038,0.244562,0.329401,0.426038,A,0,1

In [19]:
trunc19_20['B365true'].mean()

0.5487804878048781

In [20]:
trunc19_20['logittrue'].mean()

0.5

In [21]:
# Outcome value for calculating Brier Score

trunc19_20['Houtcome']= np.where(trunc19_20['FTR']=='H',1,0)
trunc19_20['Doutcome']= np.where(trunc19_20['FTR']=='D',1,0)
trunc19_20['Aoutcome']= np.where(trunc19_20['FTR']=='A',1,0)
trunc19_20

,Date,gameno,day,month,year,HomeTeam,AwayTeam,FTHG,FTAG,FTR,B365H,B365D,B365A,Tmhome,Tmaway,B365HPr,B365DPr,B365APr,B365res,winvalue,lhTMratio,predA,predD,predH,Maxprob,logitpred,logittrue,B365true,Houtcome,Doutcome,Aoutcome
224,16/05/2020,225,16,5,2020,RB Leipzig,Freiburg,1,1,D,1.30,5.50,9.00,521.90,113.98,0.724214,0.171178,0.104609,H,1,1.521453,0.170317,0.189894,0.639790,0.639790,H,0,0,0,1,0
225,16/05/2020,226,16,5,2020,Hoffenheim,Hertha,0,3,A,2.10,3.60,3.20,229.50,215.20,0.446512,0.260465,0.293023,H,0,0.064335,0.329190,0.244539,0.426271,0.426271,H,0,0,0,0,1
226,16/05/2020,227,16,5,2020,Ein Frankfurt,M'gladbach,1,3,A,2.90,3.60,2.25,207.55,266.50,0.323160,0.260323,0.416517,A,0,-0.250002,0.371955,0.246995,0.381050,0.381050,H,0,1,0,0,1
227,16/05/2020,228,16,5,2020,Fortuna Dusseldorf,Paderborn,0,0,D,2.10,3.60,3.25,81.65,24.10,0.448534,0.261645,0.289822,H,1,1.220230,0.197306,0.205380,0.597313,0.597313,H,0,0,0,1,0
228,16/05/2020,229,16,5,2020,Dortmund,Schalke 04,4,0,H,1.50,4.33,6.00,642.10,213.48,0.626401,0.216998,0.156600,H,2,1.101201,0.208825,0.211098,0.580077,0.580077,H,1,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,27/06/2020,302,27,6,2020,Dortmund,Hoffenheim,0,4,A,1.70,4.50,4.10,642.10,229.50,0.557907,0.210765,0.231327,H,0,1.028841,0.216066,0.214435,0.569499,0.569499,H,0,0,0,0,1
302,27/06/2020,303,27,6,2020,Leverkusen,Mainz,1,0,H,1.25,6.50,10.00,420.60,148.60,0.759124,0.145985,0.094891,H,2,1.040424,0.214895,0.213908,0.571197,0.571197,H,1,1,1,0,0
303,27/06/2020,304,27,6,2020,Ein Frankfurt,Paderborn,3,2,H,1.30,5.75,9.00,207.55,24.10,0.729644,0.164963,0.105393,H,2,2.153160,0.123335,0.155090,0.721575,0.721575,H,1,1,1,0,0
304,27/06/2020,305,27,6,2020,Augsburg,RB Leipzig,1,2,A,7.00,5.75,1.36,116.05,521.90,0.135787,0.165306,0.698906,A,0,-1.503455,0.556231,0.218429,0.225340,0.556231,A,1,1,0,0,1
305,27/06/2020,306,27,6,2020,Freiburg,Schalke 04,4,0,H,1.80,4.00,4.20,113.98,213.48,0.532319,0.239544,0.228137,H,2,-0.627520,0.426038,0.244562,0.329401,0.426038,A,0,1,1,0,0

In [24]:
# Model Brier score

Brierlogit = ((trunc19_20['predH'] - trunc19_20['Houtcome'])**2 +(trunc19_20['predD'] - trunc19_20['Doutcome'])**2 +\
             (trunc19_20['predA'] - trunc19_20['Aoutcome'])**2).sum()/82
Brierlogit

0.5939861306698455

In [25]:
# Bookie Brier score (lower is better)

BrierB365 = ((trunc19_20['B365HPr'] - trunc19_20['Houtcome'])**2 +(trunc19_20['B365DPr'] - trunc19_20['Doutcome'])**2 +\
             (trunc19_20['B365APr'] - trunc19_20['Aoutcome'])**2).sum()/82
BrierB365

0.5620787329712247